### PR TITLE
Fixing JSON support for images in dropdowns. Adding tests.

### LINKED ISSUE #848: Images in dropdowns no longer work after #818
PR #818 introduced a loop in `core/field_dropdown.js` that iterates over each of the options and assumes they are text, passing each one to `Blockly.utils.replaceMessageReferences`:
```js
for (var i = 0; i < options.length; i++) {
  var rawText = options[i][0];
  var localizedText = Blockly.utils.replaceMessageReferences(rawText);
  options[i][0] = localizedText;
}
```
This loop, unlike all the others, does not check that the type of `options[i][0]` is a string or an object. The zeroth index in each option is an object when you want an image: https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus#images

When this loop executes, it causes a runtime crash:
screen shot 2017-01-20 at 17 28 37

Adding a type check on `rawText` fixes the crash:
```js
if (typeof rawText === 'object') {
  continue;
}
```

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Fixes #848.

### CODE REVIEW

File: core/field_dropdown.js [hunk 1]
```diff
@@ -246,9 +246,11 @@ Blockly.FieldDropdown.prototype.trimOptions_ = function() {
   }
   // Replace message strings.
   for (var i = 0; i < options.length; i++) {
```
Comment (rachel-fenichel) [inline core/field_dropdown.js]: If it's an image, you may need to replace the alt text message string.
