### PR TITLE
fix: set flyout visbility on calling setExpanded

### LINKED ISSUE #7174: When calling `setExpanded(false)`  on a collapsible toolbox category programmatically, the flyout should be closed
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Originally reported by: https://groups.google.com/g/blockly/c/V5thY4HxQPI/m/bnlVYlzBAgAJ?utm_medium=email&utm_source=footer

If you call `setExpanded(false)` on a collapsible toolbox category, and one of the sub-categories is currently selected (i.e. its blocks are shown in the flyout). That flyout should be closed.

### Reproduction steps

1. Open the playground with the test blocks toolbox.
2. Select the "Connections > Row" toolbox category
3. Run the following code in the console `Blockly.getMainWorkspace().getToolbox().getToolboxItems()[2].setExpanded(false);`
4. Observe how the category is closed but the flyout is still open.

### Stack trace

```shell
N/A
```

### Screenshots

Step 2:
Screenshot 2023-06-15 3 02 31 PM

Step 4:
Screenshot 2023-06-15 3 03 20 PM

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by jibranabsarulislam**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #7174 

### Proposed Changes

call `setVisible(isExpanded)` on the `parentToolbox_`'s flyout to update visibility

#### Behavior Before Change

flyout is not closed when `setExpanded(false)` is called on `collapsible_category`, contrary to expected behavior

https://github.com/google/blockly/assets/70596906/cca9a332-7d9e-463f-9d78-aaf5569ead69

#### Behavior After Change

flyout is hidden along with collapsed category

https://github.com/google/blockly/assets/70596906/ccd9b5dd-9b33-46db-aea5-ab09296bd121

### Reason for Changes

fulfilling expected behavior in every case

### Test Coverage

tested full functionality of expand/collapse by opening, switching, and unfocus clicking the flyout/collapsible regions before and after changes 

### Documentation

updated setExpanded` docstring

### CODE REVIEW

**Comment by jibranabsarulislam** [comment]
please let me know of any redundancies that may arise with setting the flyout's `display` attribute. I'm going to double check on my end as well. thank you in advance!

File: core/toolbox/collapsible_category.ts [hunk 1]
```diff
@@ -200,6 +200,7 @@ export class CollapsibleToolboxCategory
       this.subcategoriesDiv_!.style.display = 'none';
       this.closeIcon_(this.iconDom_);
     }
+    this.parentToolbox_.getFlyout()?.setVisible(isExpanded);
```
Comment (BeksOmega) [inline core/toolbox/collapsible_category.ts:203]: I believe we only want to do this when `isExpanded === false`! Otherwise when we expand a category, it opens the last open flyout, which may not even be contained within the collapsible category.

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Thank you for the fix! This is looking good :D Just one change and then this should be good to go!
