### PR TITLE
Fix apostrophe in tooltips and helpurls

### LINKED ISSUE #1045: Apostrophe in tooltip in Blockly Factory
Hello, I found some issue with Blocky Factory. Webpage doesnt work after insert ' to Tooltip. After that can't export blocks and toolbox.
This issue can be solved with adding \ before every '.
Hope i help, have a nice day

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Fixes #1045

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/1111)

### CODE REVIEW

File: demos/blockfactory/factory_utils.js [hunk 1]
```diff
@@ -352,8 +352,8 @@ FactoryUtils.formatJavaScript_ = function(blockType, rootBlock, workspace) {
 
   var tooltip = FactoryUtils.getTooltipFromRootBlock_(rootBlock);
   var helpUrl = FactoryUtils.getHelpUrlFromRootBlock_(rootBlock);
-  code.push("    this.setTooltip('" + tooltip + "');");
-  code.push("    this.setHelpUrl('" + helpUrl + "');");
+  code.push(' this.setTooltip(' + JSON.stringify(tooltip) + ');');
```
Comment (RoboErikG) [inline demos/blockfactory/factory_utils.js]: does JSON.stringify add single quotes around the contents?

Comment (rachel-fenichel) [inline demos/blockfactory/factory_utils.js]: Double quotes, but yes.

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly/1111#-:-KkNsrbXDqixVwAlkDdU:bnfp4nl)*
