### PR TITLE
fix: dispose performance

### LINKED ISSUE #6890: Improve performance of deleting blocks
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Deleting the top block of the spaghetti code stack on master (https://github.com/google/blockly/commit/4125fd31534dd9f450219259b9ccb3c1495605c9) takes ~1670ms, and `checkAndDelete` takes ~1000ms.

Screenshot 2023-03-09 12 06 55 PM

On  develop (https://github.com/google/blockly/commit/c0934216f8ece4261f21977bc89ea92e8483d468) it takes ~720 seconds, with `checkAndDelete` taking ~360ms.

### Reproduction steps

1. Go to the playground
2. Hit the "spaghetti" or "JSO spaghetti" test buttons.
3. Go to the performance tab of the chrome devtools.
4. Start a recording
5. Delete the top block in the spaghetti stack.
6. Stop the recording.

### Stack trace

_No response_

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #6890 

### Proposed Changes

Improves performance of deleting blocks.

See #6890 for previous performance. The new performance is ~300ms total, and ~100ms for `checkAndDelete`.

### Reason for Changes

Speeeed

### Test Coverage

Manual testing + fixing failing tests.

Added one test to check that blocks do not receive their own delete events.

### Documentation

N/A

### Additional Information

We save an extra 20ms after #6876 is merged.

Best to review this commit-wise since there is some code reorganization.

### CODE REVIEW

File: core/block.ts [hunk 1]
```diff
@@ -313,44 +313,34 @@ export class Block implements IASTNodeLocation, IDeletable {
...
     if (eventUtils.isEnabled()) {
+      // Constructing the delete event is costly. Only perform if necessary.
       eventUtils.fire(new (eventUtils.get(eventUtils.BLOCK_DELETE))(this));
     }
-    eventUtils.disable();
+    this.workspace.removeTopBlock(this);
+    this.disposeInternal();
+  }
+
+  protected disposeInternal() {
```
Comment (rachel-fenichel) [inline core/block.ts:327]: Add comment (standard documentation, + explaining what goes in `dispose` and what goes in `disposeInternal`).

File: core/block.ts [hunk 2]
```diff
@@ -313,44 +313,34 @@ export class Block implements IASTNodeLocation, IDeletable {
...
+    if (this.isDeadOrDying()) return;
+
+    if (this.onchangeWrapper_) {
+      this.workspace.removeChangeListener(this.onchangeWrapper_);
```
Comment (rachel-fenichel) [inline core/block.ts:331]: Will the existing change listener trigger on the call to `unplug` on line 318?

File: core/icon.ts [hunk 3]
```diff
@@ -79,8 +79,11 @@ export abstract class Icon {
 
   /** Dispose of this icon. */
   dispose() {
-    dom.removeNode(this.iconGroup_);  // Dispose of and unlink the icon.
-    this.setVisible(false);           // Dispose of and unlink the bubble.
+    if (!this.getBlock().isDeadOrDying()) {
+      dom.removeNode(this.iconGroup_);
+    }
+    // TODO: Check if this is necessary.
```
Comment (rachel-fenichel) [inline core/icon.ts:85]: Nit: associate todo with an issue

File: core/field.ts [hunk 4]
```diff
@@ -489,14 +489,11 @@ export abstract class Field<T = any> implements IASTNodeLocationSvg,
   dispose() {
     dropDownDiv.hideIfOwner(this);
     WidgetDiv.hideIfOwner(this);
-    Tooltip.unbindMouseEvents(this.getClickTarget_());
 
-    if (this.mouseDownWrapper_) {
-      browserEvents.unbind(this.mouseDownWrapper_);
+    if (!this.getSourceBlock()?.isDeadOrDying()) {
```
Comment (rachel-fenichel) [inline core/field.ts:493]: Sweet, I like this optimization.

File: core/block_animations.ts [hunk 5]
```diff
@@ -39,6 +39,9 @@ let wobblingBlock: BlockSvg|null = null;
  * @internal
  */
 export function disposeUiEffect(block: BlockSvg) {
+  // Disposing is going to take so long the animation won't playanyway.
```
Comment (rachel-fenichel) [inline core/block_animations.ts:42]: nit: space between "play" and "anyway"

File: core/block.ts [hunk 6]
```diff
@@ -313,44 +313,34 @@ export class Block implements IASTNodeLocation, IDeletable {
...
-      // First, dispose of all my children.
-      for (let i = this.childBlocks_.length - 1; i >= 0; i--) {
-        this.childBlocks_[i].dispose(false);
-      }
-      // Then dispose of myself.
-      // Dispose of all inputs and their fields.
-      for (let i = 0, input; input = this.inputList[i]; i++) {
-        input.dispose();
-      }
+      [...this.childBlocks_].forEach((c) => c.disposeInternal());
```
Comment (rachel-fenichel) [inline core/block.ts:340]: This used to use the original array and go backwards. Now it uses a copy and goes forward. Why the change?

**Review by rachel-fenichel — COMMENTED** [review]
Overall looks good. I have some questions about how certain changes preserve old behaviour, but I'll try to find you to discuss in-person.

File: core/block.ts (hunk 2 above)
Comment (BeksOmega) [reply core/block.ts:342]: Added the removal to `dispose` as well, with explanatory comment.

File: core/block.ts (hunk 6 above)
Comment (BeksOmega) [reply core/block.ts]: So we discussed yesterday, and I said the issue was that `setParent(null)` updates the `childBlocks_` of the parent block. So calling `dispose` on children would mutate the array we were looping over. We could either deal with this by looping backwards (as previous) or by looping over a copy that doesn't get mutated.

However! I checked it again after we chatted and since we're no longer calling `unplug` on every block, we're also not calling `setParent(null)` on every block. So the array isn't being mutated at all, and we can just loop over it directly =)

File: core/icon.ts (hunk 3 above)
Comment (BeksOmega) [reply core/icon.ts:85]: It is necessary because the bubble lives on the bubble canvas, and is not an SVG element of the block. It will not get automatically garbage collected, so we need to dispose of it separately.

**Review by rachel-fenichel — APPROVED** [review]
