### PR TITLE
Making all blocks use the MSG colour values.

### LINKED ISSUE #1648: Overriding color constants does not override all blocks with given color
### Problem statement

Overriding color constants does not override all blocks with given color.

### Expected Behavior

Overriding a Blockly color constant after loading the `blocks_compressed.js` and before constructing a block (ideally before injecting Blockly) should affect all blocks using the color constant.

### Actual Behavior

Several block types have the incorrect color, at least among the text blocks.

### Steps to Reproduce

1. Add the following lines to the top of the first `<script>` in the Playground (right after `'use strict'`):

```
Blockly.Msg.TEXTS_HUE = "#193863";  // dark blue
```

2. Load the Playground and open the text blocks toolbox category. Note the mix of block colors:

screen shot 2018-03-29 at 10 59 01 am

### Operating System and Browser

 * Desktop Chrome

### PR DESCRIPTION
**Pull request by AnmAtAnm**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#1648 

### Proposed Changes

Making all blocks use the MSG colour values.

 * Deprecating Blockly.Constants.Lists.HUE and similar constants.
 * Removing deprecated Blockly.Blocks.lists.HUE constants.
 * Allowing message references in the Block.setColour() parameter.

### Reason for Changes

Since the conversion from JavaScript to JSON block definitions was never completed, several blocks used the old colour constants, while JSON use MSG constants. This made it difficult to change the colors on Blockly's predefined blocks.

### Test Coverage

I added the following lines to `playground.html` and then loaded all blocks in all categories, including the dynamic variables category.

```js
Blockly.Msg.LOGIC_HUE = '#193863';  // dark blue
Blockly.Msg.LOOPS_HUE = '#193863';
Blockly.Msg.MATH_HUE = '#193863';
Blockly.Msg.TEXTS_HUE = '#193863';
Blockly.Msg.LISTS_HUE = '#193863';
Blockly.Msg.COLOUR_HUE = '#193863';
Blockly.Msg.VARIABLES_HUE = '#193863';
Blockly.Msg.VARIABLES_DYNAMIC_HUE = '#193863';
Blockly.Msg.PROCEDURES_HUE = '#193863';
```

Additionally, I instantiated all blocks that have mutators and opened the mutator windows, checking the color of the configuration blocks.

Finally, I added varying combinations of the following lines to test for the console warnings:

```js
Blockly.Blocks.logic.HUE = "#193863"; // dark blue
Blockly.Constants.Logic.HUE = "#193863";
Blockly.Blocks.loops.HUE = "#193863";
Blockly.Constants.Loops.HUE = "#193863";
Blockly.Blocks.colour.HUE = "#193863";
Blockly.Constants.Colour.HUE = "#193863";
Blockly.Blocks.math.HUE = "#193863";
Blockly.Constants.Math.HUE = "#193863";
Blockly.Blocks.texts.HUE = "#193863";
Blockly.Constants.Text.HUE = "#193863";
Blockly.Blocks.lists.HUE = "#193863";
Blockly.Constants.Lists.HUE = "#193863";
Blockly.Blocks.variables.HUE = "#193863";
Blockly.Constants.Variables.HUE = "#193863";
Blockly.Constants.VariablesDynamic.HUE = "#193863";
Blockly.Blocks.procedures.HUE = "#193863";
```

Tested on:
 * Desktop Chrome

### CODE REVIEW

File: core/blockly.js [hunk 1]
```diff
@@ -562,6 +562,80 @@ Blockly.isNumber = function(str) {
   return /^\s*-?\d+(\.\d+)?\s*$/.test(str);
 };
 
+/**
+ * Checks old colour constants are not overwritten by the host application.
+ * If a constant is overwritten, it prints a console warning directing the
+ * developer to use the equivalent Msg constant.
```
Comment (rachel-fenichel) [inline core/blockly.js]: @package, no underscore at the end of the name.

File: core/blockly.js [hunk 2]
```diff
@@ -562,6 +562,80 @@ Blockly.isNumber = function(str) {
...
+  Blockly.checkBlockColourConstant_(
+      'VARIABLES_DYNAMIC_HUE', ['Constants', 'VariablesDynamic', 'HUE'], /* removed */ false);
+  Blockly.checkBlockColourConstant_(
+      'PROCEDURES_HUE', ['Blocks', 'procedures', 'HUE'], /* removed */ true);
+  // Blockly.Constants.Procedures.HUE never existed.
+};
+
+/**
+ * Checks for a constant in the Blockly namespace, verifying it either does
+ * not extist (if flagged as removed) or has the same value as the Msg
```
Comment (rachel-fenichel) [inline core/blockly.js]: Nit: "exist"

@private

File: core/block.js [hunk 3]
```diff
@@ -657,19 +657,28 @@ Blockly.Block.prototype.getHue = function() {
...
 /**
  * Change the colour of a block.
- * @param {number|string} colour HSV hue value, or #RRGGBB string.
+ * @param {number|string} colour HSV hue value (0 to 360), #RRGGBB string,
+ *     or a message reference string pointing to one of those two values.
  */
 Blockly.Block.prototype.setColour = function(colour) {
-  var hue = Number(colour);
+  var dereferenced = goog.isString(colour) ?
+          Blockly.utils.replaceMessageReferences(colour) : colour;
```
Comment (rachel-fenichel) [inline core/block.js]: Fix indent (+4 spaces from the line above; I think I've turned off checking on ternary expressions).

File: core/block.js [hunk 4]
```diff
@@ -657,19 +657,28 @@ Blockly.Block.prototype.getHue = function() {
...
+
+  var hue = Number(dereferenced);
   if (!isNaN(hue) && 0 <= hue && hue <= 360) {
     this.hue_ = hue;
     this.colour_ = Blockly.hueToRgb(hue);
-  } else if (goog.isString(colour) && /^#[0-9a-fA-F]{6}$/.test(colour)) {
-    this.colour_ = colour;
+  } else if (goog.isString(dereferenced) &&
+        /^#[0-9a-fA-F]{6}$/.test(dereferenced)) {
```
Comment (rachel-fenichel) [inline core/block.js]: Fix indent (+4 spaces from the line above).

File: core/blockly.js [hunk 5]
```diff
@@ -562,6 +562,82 @@ Blockly.isNumber = function(str) {
...
+ * @private
+ */
+Blockly.checkBlockColourConstant_ = function(
+    msgName, blocklyNamePath, removed) {
+  var namePath = 'Blockly';
+  var value = Blockly;
+  for (var i =0; i < blocklyNamePath.length; ++i) {
+    namePath += '.' + blocklyNamePath[i];
+    if (value) {
+      value = value[blocklyNamePath[i]];
```
Comment (NeilFraser) [inline core/blockly.js:626]: By spidering over Blockly, this prevents the Closure Compiler from tree-shaking effectively. This single line increases the size of the compressed file in advanced compilation by 10%.
