### PR TITLE
Include oldCoordinate and oldContents in ws comment event serialization

### LINKED ISSUE #4527: Workspace Comment Change event does not serialize/deserialize correctly
**Describe the bug**

Workspace comment `toJson` and `fromJson` use different property names (`newValue` and `newContents`) to store the value for `newContents_` and does not serialize `oldContents_` at all.

**Expected behavior**

`toJson` and `fromJson` should store and retrieve `oldContents_` and `newContents_` correctly.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #4527

### Proposed Changes

Includes `oldContents` and `oldCoodinate` in serialization/deserialization of workspace comment events

#### Behavior Before Change

Workspace comment change events did not serialize the `oldContents` property and workspace comment move events did not serialize the `oldCoordinate` property.

#### Behavior After Change

Workspace comment change events serializes `oldContents` property and workspace comment move events serializes the `oldCoordinate` property.

### Test Coverage

Ran mocha tests.

 * Desktop Chrome

### Additional Information

Adding comment move event tests tracked as part of #4577.

### CODE REVIEW

File: core/events/ws_comment_events.js [hunk 1]
```diff
@@ -358,6 +360,10 @@ Blockly.Events.CommentMove.prototype.setOldCoordinate = function(xy) {
 // TODO (#1266): "Full" and "minimal" serialization.
 Blockly.Events.CommentMove.prototype.toJson = function() {
   var json = Blockly.Events.CommentMove.superClass_.toJson.call(this);
+  if (this.newCoordinate_) {
```
Comment (maribethb) [inline core/events/ws_comment_events.js:363]: should this be `this.oldCoordinate_`?

**Review by maribethb — APPROVED** [review]

File: core/events/ws_comment_events.js (hunk 1 above)
Comment (moniika) [reply core/events/ws_comment_events.js]: Yes. Updated.
