### PR TITLE
fix(events): Simplify `filter` function, add new `enqueueEvent` function

### LINKED ISSUE #2037: controls_if: Mutation actions do not undo correctly
### Problem statement

Undo does not work correctly when `controls_if` mutator edit actions are interleaved with normal actions.

### Expected Behavior

One undo step should undo to the previous step, maintaining connections unaffected by the edit.

### Actual Behavior

A block connected to an if block where an undo reverts a mutation may also disconnect the child, even when the connected input is not (supposed to be) affected by the mutation.

### Steps to Reproduce

1. Open the playground and create the following structure:
screen shot 2018-08-30 at 2 16 52 pm
2. Next, make the following edits:
  a. Add an "else if" in the mutator.
  b. Connect the loop block to the newly created second statement connection
  c. Add an "else" to the end, within the mutator.

The results should look like this:
screen shot 2018-08-30 at 2 27 54 pm

3. Undo one step, removing the last connection.
screen shot 2018-08-30 at 2 29 23 pm

Note that making what was supposed to be a single step, editing the last connection via the mutator workspace, it has also disconnected the loop block.

### PR DESCRIPTION
**Pull request by cpcallen**
## The basics

- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #2037, #8225

### Proposed Changes

* Remove the broken `BlockChange` event reordering code from `filter`.  Instead, do necessary event reordering in a new (and hopefully more robust and less buggy) `enqueueEvent` function called from `fireInternal` as events are fired.
* Since (as of #8537) we don't filter in undo any more, and filtering in reverse order is confusing and can cause problems, prepare to remove this opportunity for error by deprecating calling `filter` with `forward=false`.
* Simplify `filter` by having it consider only adjacent events in the queue for merging.  Previously any events in the queue could potentially be merged if they were of suitable (typically identical) `.type`, even if other events had occurred between them (with the sole exception of `BlockMove` events, which would only be merged with adjacent ones).  This could potentially result in replay failures during undo/redo/mirroring, though it is unknown whether any such problems occurred in practice.
* Use `for…of` loop where appropriate.
* Make filter reason-merging code more concise.
* Use arrow functions when calling `Array.prototype.filter`.

### Reason for Changes

* Remove code from `filter` that has been the source of multiple current and previous bugs, and actively breaks other attempts to fix those bugs (e.g. by emitting events in the correct order to start with).
* Simplify `filter` so it is easier to reason about its behaviour.

### Test Coverage

* Added unit tests for `enqueueEvent`.
* There are existing unit tests for `filter`, none of which fail due to the changes made in this PR.

### CODE REVIEW

**Comment by cpcallen** [comment]
> ## The basics
> * [x]  I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)
> 
> ## The details
> ### Resolves
> Fixes #2037, #8225
> 
> ### Proposed Changes
> * Remove the broken `BlockChange` event reordering code from `filter`.  Instead, do necessary event reordering in a new (and hopefully more robust and less buggy) `enqueueEvent` function called from `fireInternal` as events are fired.
> * Since (as of [refactor(events): Don't filter events before undo #8537](https://github.com/google/blockly/pull/8537)) we don't filter in undo any more, and filtering in reverse order is confusing and can cause problems, prepare to remove this opportunity for error by deprecating calling `filter` with `forward=false`.
> * Simplify `filter` by having it consider only adjacent events in the queue for merging.  Previously any events in the queue could potentially be merged if they were of suitable (typically identical) `.type`, even if other events had occurred between them (with the sole exception of `BlockMove` events, which would only be merged with adjacent ones).  This could potentially result in replay failures during undo/redo/mirroring, though it is unknown whether any such problems occurred in practice.
> * Use `for…of` loop where appropriate.
> * Make filter reason-merging code more concise.
> * Use arrow functions when calling `Array.prototype.filter`.
> 
> ### Reason for Changes
> * Remove code from `filter` that has been the source of multiple current and previous bugs, and actively breaks other attempts to fix those bugs (e.g. by emitting events in the correct order to start with).
> * Simplify `filter` so it is easier to reason about its behaviour.
> 
> ### Test Coverage
> * Added unit tests for `enqueueEvent`.
> * There are existing unit tests for `filter`, none of which fail due to the changes made in this PR.

### Additional Info

Strictly speaking, making the `forward` parameter of `filter` default to `true` is a breaking change, as JS users would previously have observed it defaulting to falsy `undefined`.  My reasoning to overlook this is that I suspect very few developers use this function directly (to the point that I think we should consider deprecating its export), and the likelihood of any of them calling it with no second parameter, _intending that to request filtering in reverse order_, seems very remote.

Nevertheless the change adding a default could be removed if desired.

File: core/events/utils.ts [hunk 1]
```diff
@@ -151,18 +162,21 @@ function fireNow() {
...
- * made it difficlut to reason about how events are processed for
- * undo/redo, so both the call from undo and the post-processing code
- * was later removed.
+ * but the mutation of events by this function was the cause of issue
+ * #7026 (note that events would combine differently in reverse order
+ * vs. forward order).  The originally-chosen fix for this was the
+ * addition (in PR #7069) of code to fireNow to post-filter the
+ * .undoStack_ and .redoStack_ of any workspace that had just been
+ * involved in dispatching events; this apparently resolved the issue
+ * but added considerable additional complexity and made it difficlut
```
Comment (gonfunko) [inline core/events/utils.ts:217]: nit: difficult

File: core/events/utils.ts [hunk 2]
```diff
@@ -79,9 +79,20 @@ export type BumpEvent =
...
 
 /**
- * Create a custom event and fire it.
+ * Enqueue an event to be dispatched to change listeners.
  *
- * @param event Custom data for event.
+ * Notes:
+ *
+ * - Events are enqueued until a timeout, generally after rendering is
+ *   complete but or at the end of the current microtask, if not
```
Comment (gonfunko) [inline core/events/utils.ts:87]: nit: errant "but"

File: tests/mocha/event_test.js [hunk 3]
```diff
@@ -1102,6 +1122,165 @@ suite('Events', function () {
...
+      event.newCoordinate = new Blockly.utils.Coordinate(0, 0);
+      return event;
+    }
+
+    function newConnectEvent(parent, child, inputName, workspaceId) {
+      const event = new Blockly.Events.BlockMove(child);
+      event.workspaceId = workspaceId;
+      event.oldParentId = undefined;
+      event.oldInputName = undefined;
+      event.oleCoordinate = new Blockly.utils.Coordinate(0, 0);
```
Comment (gonfunko) [inline tests/mocha/event_test.js:1145]: nit: oldCoordinate

File: core/events/utils.ts [hunk 4]
```diff
@@ -226,14 +229,17 @@ function enqueueEvent(event: Abstract) {
  *
  * @param queueIn Array of events.
  * @param forward True if forward (redo), false if backward (undo).
+ *     This parameter is deprecated: true is now the default and
+ *     calling filter with it false will in future not be supported.
```
Comment (gonfunko) [inline core/events/utils.ts:237]: nit: "with it set to"?

**Review by gonfunko — APPROVED** [review]

File: tests/mocha/event_test.js (hunk 3 above)
Comment (cpcallen) [reply tests/mocha/event_test.js:1145]: I am concerned that this did not cause a test failure…
