### PR TITLE
fix: Don't repeatedly recreate the last marker block during a drag.

### LINKED ISSUE #6839: Insertion Marker Manager creates unused marker blocks.
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When a stack of block is dragged (even on an otherwise empty workspace), every pixel of drag triggers the creation of a new insertion marker block.  Despite that no insertion marker is shown on screen.

This is a performance issue.  It is also the source of unneeded calls to domToMutation.
Reported externally: https://groups.google.com/g/blockly/c/-eK657F9qCM

### Reproduction steps

1. Add a console.log('New Marker Block!') into the top of createMarkerBlock function of insertion_marker_manager.js
2. On an empty workspace, create a stack of any two statement blocks.
3. Open the console, and drag the stack of two blocks.

Expect: zero (or maybe one) instances of 'New Marker Block!'
Actual: one 'New Marker Block!' per pixel dragged.

### Stack trace

```shell
domToMutation	@	logic.js:332
createMarkerBlock	@	insertion_marker_manager.js:181
initAvailableConnections	@	insertion_marker_manager.js:239
updateAvailableConnections	@	insertion_marker_manager.js:102
getCandidate	@	insertion_marker_manager.js:290
update	@	insertion_marker_manager.js:148
drag	@	block_dragger.js:140
handleMove	@	gesture.js:466
wrapFunc	@	browser_events.js:59
```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

Fixes  #6839

### Proposed Changes
#5722 introduced logic to update the available connections (and marker block) for a block being dragged as it was being dragged in order to make the marker block reflect changes to the connections of the block being dragged that happened during the drag. The insertion marker corresponding the first block in the stack being dragged was only regenerated when (a) it was shown and (b) its connections were inconsistent with those on the corresponding insertion marker block. However, the insertion marker corresponding to the last block in the stack was recreated every time the drag moved. This PR updates the insertion marker manager to only create the insertion marker block corresponding to the last block in the stack being dragged (a) at the beginning of the drag and (b) in the event of the same sort of mismatch during showing that would cause the insertion marker block corresponding to the first block in the stack being dragged to be regenerated.

#### Behavior Before Change
Numerous useless block creations.

#### Behavior After Change
Insertion marker blocks are only created on an as-needed basis.

### CODE REVIEW

File: core/insertion_marker_manager.ts [hunk 1]
```diff
@@ -303,15 +303,9 @@ export class InsertionMarkerManager {
...
       available.push(lastOnStack);
       this.lastOnStack = lastOnStack;
-      if (this.lastMarker) {
-        eventUtils.disable();
-        try {
-          this.lastMarker.dispose();
-        } finally {
-          eventUtils.enable();
-        }
+      if (!this.lastMarker) {
```
Comment (BeksOmega) [inline core/insertion_marker_manager.ts:306]: Instead of doing this here, can you move it to the constructor & update the JSDoc for this function?

Like:
```
this.firstMarker = /* etc */;
this.initAvailableConnections();
if (this.lastOnStack) this.lastMarker = this.createMarkerBlock(/* etc */);
```

File: core/insertion_marker_manager.ts [hunk 2]
```diff
@@ -561,8 +555,31 @@ export class InsertionMarkerManager {
...
-      insertionMarker = isLastInStack ? this.lastMarker : this.firstMarker;
+      if (isLastInStack && this.lastOnStack) {
+        if (this.lastMarker) {
+          eventUtils.disable();
+          try {
+            this.lastMarker.dispose();
+          } finally {
+            eventUtils.enable();
+          }
+        }
```
Comment (BeksOmega) [inline core/insertion_marker_manager.ts:566]: Can you break this out into a sub procedure? E.g. `disposeInsertionMarker`

File: core/insertion_marker_manager.ts [hunk 3]
```diff
@@ -561,8 +555,31 @@ export class InsertionMarkerManager {
...
+        insertionMarker = this.lastMarker;
+      } else {
+        if (this.firstMarker) {
+          eventUtils.disable();
+          try {
+            this.firstMarker.dispose();
+          } finally {
+            eventUtils.enable();
+          }
+        }
```
Comment (BeksOmega) [inline core/insertion_marker_manager.ts:578]: Oof, were we just eating memory before?

**Review by BeksOmega — APPROVED** [review]

File: core/insertion_marker_manager.ts (hunk 3 above)
Comment (gonfunko) [reply core/insertion_marker_manager.ts]: I assume the GC would have cleaned up after us eventually since the marker would have become unreachable, but you introduced this logic in #4184 to fix an issue so I'm carrying it forward.

File: core/insertion_marker_manager.ts (hunk 2 above)
Comment (gonfunko) [reply core/insertion_marker_manager.ts]: Good call, done!

File: core/insertion_marker_manager.ts (hunk 1 above)
Comment (gonfunko) [reply core/insertion_marker_manager.ts]: Done.
