### PR TITLE
fix: Fix bug that prevented editing workspace comments on Firefox.

### LINKED ISSUE #8768: Workspace comments aren't editable in Firefox
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

If you create a workspace comment in Firefox, it's not possible to edit or select its text. Works fine in other browsers, and block comments work fine in Firefox, with seemingly the same DOM structure.

### Browsers

Firefox desktop

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8768

### Proposed Changes
This PR fixes a bug that prevented editing the text of workspace comments on Firefox.

### CODE REVIEW

File: core/comments/rendered_workspace_comment.ts [hunk 1]
```diff
@@ -208,8 +208,15 @@ export class RenderedWorkspaceComment
   private startGesture(e: PointerEvent) {
     const gesture = this.workspace.getGesture(e);
     if (gesture) {
-      gesture.handleCommentStart(e, this);
-      this.workspace.getLayerManager()?.append(this, layers.BLOCK);
+      const textArea = this.view.getTextArea();
```
Comment (rachel-fenichel) [inline core/comments/rendered_workspace_comment.ts:211]: Can you do this with `isTargetInput` from `browser_events.ts` instead?

Comment (gonfunko) [reply core/comments/rendered_workspace_comment.ts]: Ooh, yes! Much nicer, thank you!

File: core/comments/rendered_workspace_comment.ts [hunk 2]
```diff
@@ -208,8 +208,14 @@ export class RenderedWorkspaceComment
...
     const gesture = this.workspace.getGesture(e);
     if (gesture) {
-      gesture.handleCommentStart(e, this);
-      this.workspace.getLayerManager()?.append(this, layers.BLOCK);
+      if (browserEvents.isTargetInput(e)) {
+        // If the text area was the focus, don't allow this event to bubble up
+        // and steal focus away from the editor/comment.
+        e.stopPropagation();
+      } else {
+        gesture.handleCommentStart(e, this);
```
Comment (rachel-fenichel) [inline core/comments/rendered_workspace_comment.ts:216]: Next question: why is this not already fixed by the other uses of `isTargetInput` in `inject.ts` and `gesture.ts`?

Comment (gonfunko) [reply core/comments/rendered_workspace_comment.ts:216]: `handleCommentStart()` doesn't ever call `doStart()`, where `isTargetInput()` is checked; `handleWsStart` does, but by the time that's called the event has already bubbled up to the workspace and stolen focus away from the textarea, so it's too late. Likewise, inject.ts only checks it for keydown and contextmenu events, not clicks.

**Review by rachel-fenichel — APPROVED** [review]
