### PR TITLE
Fix serialization of workspace comment events and add tests

### LINKED ISSUE #4527: Workspace Comment Change event does not serialize/deserialize correctly
**Describe the bug**

Workspace comment `toJson` and `fromJson` use different property names (`newValue` and `newContents`) to store the value for `newContents_` and does not serialize `oldContents_` at all.

**Expected behavior**

`toJson` and `fromJson` should store and retrieve `oldContents_` and `newContents_` correctly.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #4527

### Proposed Changes

- Updates logic in serialization of methods of workspace comment events to be consistent.
- Adds tests for workspace comment events and finished loading event

### Reason for Changes

- Workspace comment events were not serializing/deserializing properly.
- Tests are good.

### Test Coverage

Ran mocha tests

### Additional Information

Filed #4577 to track adding more complex tests for testing coordinate properties of move events (for block move and comment move).

### CODE REVIEW

File: tests/mocha/event_test.js [hunk 1]
```diff
@@ -593,6 +593,7 @@ suite('Events', function() {
           oldXml: '<shadow xmlns="https://developers.google.com/blockly/xml"' +
               ' type="simple_test_block" id="testBlockId2"></shadow>',
           ids: [thisObj.shadowBlock.id], recordUndo: false})},
+      // TODO(4577) Test serialization of move event coordinate properties.
```
Comment (maribethb) [inline tests/mocha/event_test.js:596]: I think you need `#4577` instead to get some tools to auto link to the issue (same below)

**Review by maribethb — APPROVED** [review]

File: tests/mocha/event_test.js (hunk 1 above)
Comment (moniika) [reply tests/mocha/event_test.js]: Nice catch! Fixed.
