### PR TITLE
Set correct defaults for Fields (#3179)

### LINKED ISSUE #3177: FieldNumber interprets null min/max as 0.
**Describe the bug**

Converting to Number(value) in FieldNumber had the effect of causing nulls passed to the constructor for min/max to be interpreted as 0. We need to explicitly check for null and set them to +/- infinity as appropriate.

**To Reproduce**

1. Select test blocks in the playground
2. Drag out a rounding to 10 block from the validators category
3. Try to set the value to anything other than 0

**Expected behavior**

value gets rounded to the nearest 10

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### PR DESCRIPTION
**Pull request by RoboErikG**
null was being converted to 0 by Number() when it should cause the
default value to be set instead. This updates FieldNumber and
FieldAngle to handle nulls correctly. Also update jsdoc.

Fixes #3177

## The basics

- [ ] I branched from develop
- [ ] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Test Coverage

Tested on:

### Additional Information

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/3195)

### CODE REVIEW

File: tests/mocha/field_number_test.js [hunk 1]
```diff
@@ -247,6 +247,12 @@ suite('Number Fields', function() {
           numberField.setValue(123.456);
           assertValue(numberField, 123);
         });
+        test('null', function() {
```
Comment (rachel-fenichel) [inline tests/mocha/field_number_test.js]: It's weird to me that you're testing whether the number is set instead of checking what the max/min/precision values on the field are.  Why?

File: core/field_angle.js [hunk 2]
```diff
@@ -172,20 +172,32 @@ Blockly.FieldAngle.prototype.configure_ = function(config) {
   if (typeof clockwise == 'boolean') {
     this.clockwise_ = clockwise;
   }
-  var offset = Number(config['offset']);
-  if (!isNaN(offset)) {
-    this.offset_ = offset;
+
```
Comment (rachel-fenichel) [inline core/field_angle.js]: If null -> do nothing -> use the value set on Blockly.FieldAngle, correct?

Worth a comment if so.

File: tests/mocha/field_number_test.js (hunk 1 above)
Comment (RoboErikG) [reply tests/mocha/field_number_test.js]: Whoops. I was copying the way the previous tests work and didn't think too much about it. Probably makes sense to check the values directly, though that can be a followup since this is a cherry-pick.

File: core/field_angle.js (hunk 2 above)
Comment (RoboErikG) [reply core/field_angle.js]: Correct. I'll add that in a followup pr as well (though not worth cherry-picking).

**Comment by rachel-fenichel** [comment]
Ah, I didn't see that this is a cherry-pick.

Approve.
