### PR TITLE
Don't render children of collapsed blocks

### LINKED ISSUE #4229: Collapsed block performance
**Describe the bug**

Hidden child blocks of collapsed blocks are being re-rendered when a block is being dragged to connect to it.
This causes unnecessary performance issues.

**To Reproduce**

1. Go to the Blockly playground, and use the Spaghetti option to add a long list of connected blocks to the playground.
2. Click on each of the top level if statements and collapse them.
3. Drag another block and attempt to place it in between these blocks.
4. Notice the lag.

**Expected behavior**

Even though there aren't that many visible blocks, we are still re-rendering the block and all of it's (hidden) children as we drag a block to connect to it.

If we can't easily avoid rendering all blocks (even if they're hidden) on first pass, we can probably skip re-rendering blocks if they're hidden during re-render.

**Additional context**

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Part of #4229

### Proposed Changes

- Sets rendered state of children of collapsed blocks to false, so they are not re-rendered when the block is moved.
- Checks if child is rendered before calling `updateDisabled ` in `updateDisabled`.

### Reason for Changes

Improves performance.

### Test Coverage

Tested scenario descibed in #4229 and saw improvement in performance while testing with chrome performance tool.

Tested that issues #3784 was still fixed.

Tested issue #1967 in playground using xml:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_repeat_ext" x="88" y="138">
    <value name="TIMES">
      <shadow type="math_number">
        <field name="NUM">10</field>
      </shadow>
    </value>
    <statement name="DO">
      <block type="text_print">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT">already here 1</field>
          </shadow>
        </value>
        <next>
          <block type="text_print">
            <value name="TEXT">
              <shadow type="text">
                <field name="TEXT">already here 2</field>
              </shadow>
            </value>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="text_print" x="88" y="288">
    <value name="TEXT">
      <shadow type="text">
        <field name="TEXT">connected while collapsed</field>
      </shadow>
    </value>
  </block>
</xml>
```
And repro code:
```
  var ws = Blockly.getMainWorkspace();
  var blocks = ws.getTopBlocks();
  blocks[0].setCollapsed(true);
  blocks[0].getInput('DO').connection.connect(blocks[1].previousConnection);
  // Check that attached block is hidden/not rendered
  blocks[0].setCollapsed(false);
  // Check that all blocks are un-hidden/rendered
```

Tested on:
* Desktop Chrome

### Additional Information

n/a

### CODE REVIEW

**Comment by BeksOmega** [comment]
I think I might have changed this because of https://github.com/google/blockly/issues/1967 but I can't exactly remember.

File: core/rendered_connection.js [hunk 1]
```diff
@@ -459,6 +459,12 @@ Blockly.RenderedConnection.prototype.onFailedConnect = function(
  */
 Blockly.RenderedConnection.prototype.disconnectInternal_ = function(parentBlock,
     childBlock) {
+  // The input the child block was connected to (if any).
+  var parentInput = parentBlock.getInputWithBlock(childBlock);
+  if (parentInput && !parentInput.isVisible()) {
+    childBlock.rendered = true;
+
+  }
```
Comment (moniika) [inline core/rendered_connection.js:467]: I'm worried about whether this may have unintended side effects.

File: core/rendered_connection.js [hunk 2]
```diff
@@ -459,6 +459,11 @@ Blockly.RenderedConnection.prototype.onFailedConnect = function(
  */
 Blockly.RenderedConnection.prototype.disconnectInternal_ = function(parentBlock,
     childBlock) {
+  // The input the child block was connected to (if any).
+  var parentInput = parentBlock.getInputWithBlock(childBlock);
+  if (parentInput && !parentInput.isVisible()) {
+    childBlock.rendered = true;
+  }
```
Comment (moniika) [inline core/rendered_connection.js:466]: I'm worried about whether this may have unintended side effects.

Comment (BeksOmega) [reply core/rendered_connection.js:466]: I think it looks good! Because if the block is top-level it should definitely be visible right? As long as the [nested disconnection test](https://github.com/google/blockly/blob/9ab6273e4c2fb0cd25004650d0020490294eed50/tests/mocha/block_test.js#L1444) is passing it should be fine.

I'm going to tag this with #4288 though cuz I know that `.rendered` is kinda crazy wrt collapsed blocks.

**Review by rachel-fenichel — APPROVED** [review]
