### PR TITLE
fix: Toolbox & Flyout ARIA positions (experimental)

### LINKED ISSUE #9386: Screen reader - toolbox and flyout position and count readout inconsistencies
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

When navigating the toolbox, and at least one flyout, the treeitem / block position and total counts are inconsistent and can be incorrect. See the screen recording below, noting the change from the "p5 blocks" toolbox item, into the "Misc" and "A subcategory" tree items. Also note the readout while navigating through the flyout items when inside the "p5 blocks" flyout.

### Reproduction steps

1. Use https://google.github.io/blockly-keyboard-experimentation/screenreader/
2. With a screen reader switched on, note the inconsistencies in item position and count while navigating to the last toolbox items, and flyout items.

### Stack trace

```shell

```

### Screenshots

https://github.com/user-attachments/assets/380c8f2a-e0ee-4e38-8947-990c31aec931

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by BenHenning**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9386
Fixes part of #9293

### Proposed Changes

Addresses #9386 through a number of changes:
- Ensures the flyout contents are reevaluated for ARIA changes whenever they themselves change (since previously `WorkspaceSvg` only recomputed its ARIA properties when one of its blocks self-registered which doesn't account for labels or buttons).
- Collapsible categories are now correctly wrapped by a group (since groups of tree items must be in a parent group).
-  Updates toolbox ARIA computations to be on content changes rather than having items self-specify recomputing the ARIA properties. This mitigates an issue with collapsible categories not updating the toolbox contents and thus being omitted.
- Introduced a separate pathway for computing tree info for flyout workspaces (vs. for the main workspace) in order to account for `FlyoutButton`s.
- Updated `FlyoutButton` to use a nested structure of `treeitem` then `button` in order to actually count correctly in the tree and still be an interactive button. The readout experience is actually better now on ChromeVox, as well, since it reads out _both_ 'Button' and 'Tree item' which is interesting. It seems screen readers are designed to look for this pattern but it only works if set up in a very particular way.

### Reason for Changes

Most of the changes here fixed incidental problems noticed while trying to address #9386 (such as the variables category not correctly accounting for the 'Create variable' button in the count, or not having the correct labels). Much of the count issues in the original issue were caused by a combination of missing some flyout items, and trying to compute the labels too early (i.e. before the categories were fully populated). 

### Test Coverage

Since this is an experimental change, no new tests were added.

### Documentation

No documentation changes are directly needed here.

### Additional Information

None.

### CODE REVIEW

**Review by BenHenning — COMMENTED** [review]
Self-review.

File: core/workspace_svg.ts [hunk 1]
```diff
@@ -2947,10 +2947,39 @@ export class WorkspaceSvg
   }
 
   recomputeAriaTree() {
-    // TODO: Do this efficiently (probably incrementally).
-    this.getTopBlocks(false).forEach((block) =>
-      this.recomputeAriaTreeItemDetailsRecursively(block),
-    );
+    // Flyout workspaces require special arrangement to account for items.
```
Comment (gonfunko) [inline core/workspace_svg.ts:2940]: This is fine for now, but note that flyouts can contain arbitrary user-defined kinds of elements, not just buttons and blocks.

**Review by gonfunko — APPROVED** [review]

File: core/workspace_svg.ts (hunk 1 above)
Comment (BenHenning) [reply core/workspace_svg.ts:2940]: Great point. I've added a TODO to specifically mention this.

**Review by BenHenning — COMMENTED** [review]
Self-review latest.

**Comment by BenHenning** [comment]
I don't think the latest change needs another review pass since it's just adding a TODO and cleaning up redundant `isFocusableNode` calls in `WorkspaceSvg`. Will go ahead and merge this once CI is done running.
