### PR TITLE
Bug Fix - Issue #3386 - Warning Bubble Dragging

### LINKED ISSUE #3386: Unable to drag a warning bubble if mouse is over text
**Describe the bug**

Unable to drag a warning bubble by text. Dragging over text instead moves the workspace.

**To Reproduce**

1. Go to the playground
2. Place a break loop inside of an if statement or a non-loop block to get a warning icon.
3. Open the warning icon. 
4. Try to drag the icon by the text on the bubble.
5. Notice how the workspace moves instead.

**Expected behavior**

Be able to drag the warning bubble from any where on the bubble.

**Screenshots**
warningbubbledrag

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### PR DESCRIPTION
**Pull request by MooseJ**
## The basics
- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#3386 

### Proposed Changes
This PR adds a mouse down event handler for the warning text elements.

### Reason for Changes

This fixes the bug in #3386 

### Test Coverage
Tested on:
Desktop Chrome
Desktop Firefox
Desktop Safari

### Documentation
No new documentation is required

### Additional Information
This logic is very similar to handling mouse down events for dragging in the Bubble Class.

Functionality after the code changes:
Alt Text

### CODE REVIEW

**Comment by MooseJ** [comment]
@googlebot I fixed it.

File: core/warning.js [hunk 1]
```diff
@@ -150,6 +156,12 @@ Blockly.Warning.prototype.createBubble = function() {
     }
   }
   this.applyColour();
+
+  // Allow the bubble to be dragged from the warning paragraph
+  if (!this.block_.workspace.options.readOnly) {
+    Blockly.bindEventWithChecks_(
```
Comment (samelhusseini) [inline core/warning.js]: This works, but there's really no point of the additional code. The backing layer (``bubbleBack_``) in bubble is handling this behaviour already. All you really need to do is not handle events on the paragraph layer. You can do this by setting ``pointer-events:none``.
I would suggest adding a css class ``blocklyNoPointerEvents`` in css.js that does: 
```
.blocklyNoPointerEvents {
  pointer-events: none;
}
```
and setting the class of the paragraph to that.

**Comment by samelhusseini** [comment]
Thanks @MooseJ!

**Comment by MooseJ** [comment]
No problem!
