### PR TITLE
Emitting event on trashcan close.

### LINKED ISSUE #4033: Trashcan should emit UI event when flyout is closed
**Describe the bug**

Trashcan does not emit UI event when trashcan is closed. 

**To Reproduce**

1. Go to Blockly playground and enable event logging
2. Open and close trashcan flyout and observe that event is only logged when flyout is opened

**Expected behavior**

Trashcan should emit event of type `Blockly.Events.UI` `element='trashcanOpen'` `newValue=false` when flyout is closed.

**Additional context**

Event emitted by trashcan flyout open was updated in #4024 but event emitting for flyout closing was not added.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#4033

### Proposed Changes

Adds logic for emitting event when trashcan is closed and adds helper for opening/closing trashcan flyout.

### Reason for Changes

Adding helpers makes the connection between showing/hiding flyout and emitting event for open/close clearer.
Event for closing trashcan flyout is consistent with behavior of other similarly named Ui events.

### Test Coverage

Tested on playground by observing event logging.

Tested on:
* Desktop Chrome

### Additional Information

The change in #4034 in combination with this change will cause event to be emitted when block is dragged out of trashcan flyout.

### CODE REVIEW

File: core/trashcan.js [hunk 1]
```diff
@@ -372,6 +372,34 @@ Blockly.Trashcan.prototype.contentsIsOpen = function() {
   return this.flyout.isVisible();
 };
 
+/**
+ * Opens the trashcan flyout.
+ */
+Blockly.Trashcan.prototype.openContents = function() {
```
Comment (rachel-fenichel) [inline core/trashcan.js:378]: I have a slight preference for `openFlyout` and `closeFlyout` instead of `openContents` and `closeContents`

Comment (moniika) [reply core/trashcan.js]: sgtm
