### PR TITLE
fix: Fix downloading screenshots on the playground.

### LINKED ISSUE #6023: Download screenshot contextual menu item is broken
**Describe the bug**

The Download Screenshot contextual menu item (on the workspace) is broken in the develop branch.

**To Reproduce**
1. Open the playground on the develop branch
2. Add some blocks
3. Right click on the workspace and choose the Download Screenshot contextual menu item.

**Expected behavior**
A screenshot of the workspace is downloaded. Instead, the following is logged to the console and nothing visibly happens:

```
playground.html?dir=rtl&toolbox=categories:245 Uncaught TypeError: Blockly.downloadScreenshot is not a function
    at Object.callback (playground.html:245:15)
    at Object.actionHandler (:8080/core/contextmenu.js:158:16)
    at MenuItem.performAction (:8080/core/menuitem.js:276:12)
    at Menu.handleClick_ (:8080/core/menu.js:387:16)
    at HTMLDivElement.wrapFunc (:8080/core/browser_events.js:86:14)
```

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves
#6023 

### Proposed Changes
This PR fixes the Download Screenshot command in the workspace contextual menu in the playgrounds.

#### Behavior Before Change
The contextual menu item had no visible effect and logged an error to the console.

#### Behavior After Change
A screenshot of the workspace is downloaded.

### CODE REVIEW

File: tests/playgrounds/screenshot.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ function workspaceToSvg_(workspace, callback, customCss) {
  * Download a screenshot of the blocks on a Blockly workspace.
  * @param {!Blockly.WorkspaceSvg} workspace The Blockly workspace.
  */
-Blockly.downloadScreenshot = function(workspace) {
+const downloadScreenshot = function(workspace) {
```
Comment (maribethb) [inline tests/playgrounds/screenshot.js:98]: Could you please add an eslint-ignore statement to silence this warning?

**Review by maribethb — APPROVED** [review]

File: tests/playgrounds/screenshot.js (hunk 1 above)
Comment (gonfunko) [reply tests/playgrounds/screenshot.js]: Just converted it to a function declaration.
