### PR TITLE
fix: Make `MenuItem` methods toggle classes immediately

### LINKED ISSUE #8801: CSS classes/state aren't updated when menu items are modified
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

The setters in MenuItem only toggle the backing field, but don't update the CSS classes attached to the menu item's DOM element, other than `setHighlighted()`. They should do so to allow for dynamically changing the state of menu items while the menu is being displayed, without having to close and reopen it.

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8801 

### Proposed Changes
This PR makes the various methods on `MenuItem` that toggle properties like checking, enabling, RTL, etc immediately update the state of the menu item without requiring the entire menu to be torn down and recreated to reflect the new state. It also adds tests for `MenuItem`.

### CODE REVIEW

File: core/menuitem.ts [hunk 1]
```diff
@@ -186,15 +198,10 @@ export class MenuItem {
...
-    const el = this.getElement();
-    if (el && this.isEnabled()) {
-      const name = 'blocklyMenuItemHighlight';
-      if (highlight) {
-        dom.addClass(el, name);
-      } else {
-        dom.removeClass(el, name);
-      }
-    }
+    this.getElement()?.classList.toggle(
```
Comment (maribethb) [inline core/menuitem.ts]: previously we were checking `this.isEnabled()` as well, should that check remain?

File: core/menuitem.ts [hunk 2]
```diff
@@ -243,4 +255,33 @@ export class MenuItem {
...
   }
+
+  /**
+   * Adds or removes the checkmark indicator on this menu item.
+   * The indicator is present even if this menu item is not checked, as long
+   * as it is checkable; its visibility is controlled with CSS.
+   *
+   * @param add True to add the checkmark indicator, false to remove it.
+   */
+  private toggleCheckbox(add: boolean) {
```
Comment (maribethb) [inline core/menuitem.ts]: the method name makes it sound like you're toggling whether the box is checked or not. what about `toggleHasCheckbox()`  or similar?

**Review by maribethb — APPROVED** [review]

File: core/menuitem.ts (hunk 1 above)
Comment (gonfunko) [reply core/menuitem.ts]: Good catch, yes! Added a test for this as well.

File: core/menuitem.ts (hunk 2 above)
Comment (gonfunko) [reply core/menuitem.ts]: Done

**Review by maribethb — APPROVED** [review]
