### PR TITLE
fix: widget positioning

### LINKED ISSUE #7491: Modifying the structure of a block does not trigger widgets to be repositioned
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If a warning icon is added or removed during field editing, the field is not rendered correctly.

related to the rendering queue and might be related to #7068 ?

### Reproduction steps

1. Open Block Factory
2. Drag two value input blocks into the inputs input. Notice how they each have a warning now due to conflicting names.
3. Change the name of one of the inputs. The warning disappears, and the underlying block is resized. But the text input html element is now in the wrong place because it did not move when the block was resized.
4. Click outside the field to end editing / close the widget div.
5. Change the name back to `NAME`. The warning reappears, causing the same problem again.

### Stack trace

_No response_

### Screenshots

Screenshot 2023-09-14 at 5 39 53 PM

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #7491

### Proposed Changes

Reorganizes a bunch of code, and makes it so that fields get `onLocationChange` call backs.

### Reason for Changes

Makes it so that fields can reposition their widgets properly.

### Test Coverage

* Tested that https://github.com/google/blockly/issues/6976 does not reproduce
* Tested that changing the window size properly repositions the div, re: https://github.com/google/blockly/issues/6915
* Tested that #7491  does not reproduce
* Tested that we did not get a significant performance drop by dragging spaghetti blocks, and also typing into the spaghetti blocks. We might have gotten a slight performance dip from splitting up the connection update operations so they're not happening contiguously (the engine can't optimize as much). But all of this code is internal so I can circle back once I've had more time to investigate.

[old-dragging.txt](https://github.com/google/blockly/files/12691991/old-dragging.txt)
[new-dragging.txt](https://github.com/google/blockly/files/12691992/new-dragging.txt)

### Documentation

N/A

### Additional Information

Might want to hold until after release?

## Deprecations

- [ ] TODO

### CODE REVIEW

**Comment by BeksOmega** [comment]
Note to self to ping code.org people about this re: their flyout field if it gets approved. I think they can use this new callback to handle the width of their field less jankily. (Since we call `onLocationChange` after every render.)

File: core/field_input.ts [hunk 1]
```diff
@@ -616,6 +617,7 @@ export abstract class FieldInput<T extends InputTypes> extends Field<
     }
     const div = WidgetDiv.getDiv();
     const bBox = this.getScaledBBox();
+    console.log(bBox);
```
Comment (BeksOmega) [inline core/field_input.ts:620]: Remove.

File: core/field_input.ts [hunk 2]
```diff
@@ -642,13 +644,13 @@ export abstract class FieldInput<T extends InputTypes> extends Field<
...
 
-    bumpObjects.bumpIntoBounds(
+    const bumped = bumpObjects.bumpIntoBounds(
       this.workspace_!,
       this.workspace_!.getMetricsManager().getViewMetrics(true),
       block,
     );
 
-    this.resizeEditor_();
+    if (!bumped) this.resizeEditor_();
```
Comment (maribethb) [inline core/field_input.ts:653]: Why do you only need to resize the editor if it wasn't bumped? Should it be the opposite?

Comment (BeksOmega) [reply core/field_input.ts:653]: If we trigger a move of the block (the block gets bumped), it triggers `onLocationChange` for all fields, so the field gets bumped that way. If we don't move the block, we still need to reposition the widget because the block might be moving relative to the top-left of the window (even though it's not moving relative to the workspace origin).

Here's what it looks like if I remove the `if (!bumped) this.resizeEditor_();` line:
Screen recording 2023-10-26 9 31 51 AM

You can see that if we do bump, repositioning is handled, but if we don't it is not handled.

**Review by maribethb — APPROVED** [review]
