### PR TITLE
fix: Make metadata tests more resilient.

### LINKED ISSUE #6768: metadata test does not work
**Describe the bug**

metadata test says

```
== metadata
Zipping the compressed files
Size of dist/blockly_compressed.js at 928193 compared to previous undefined
Size of dist/blocks_compressed.js at 109229 compared to previous undefined
Size of dist/blockly_compressed.js.gz at 182818 compared to previous undefined
Size of dist/blocks_compressed.js.gz at 18234 compared to previous undefined
SUCCESS: metadata
```

**To Reproduce**

run `npm run test`

**Expected behavior**

previous values are not undefined

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

This has been happening for a while and was not caused (or fixed) by #6763

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves
#6768

### Proposed Changes
This PR updates the metadata test to verify that the previous size of the files is not undefined, in order to trigger an explicit test failure in the situation reported in #6768. It also updates the check_metadata.sh file to remove errant whitespace before the file sizes that was causing the regex in test_tasks.js to fail to identify the old file sizes when running the test. Finally, it updates update_metadata.sh to strip whitespace when updating the file sizes in check_metadata.sh to avoid this issue recurring.

#### Behavior Before Change
Metadata test scripts didn't actually check the change in filesize and passed regardless.

#### Behavior After Change
Metadata test scripts work properly.

### CODE REVIEW

File: scripts/gulpfiles/test_tasks.js [hunk 1]
```diff
@@ -165,7 +165,11 @@ function compareSize(file, expected) {
   const stat = fs.statSync(name);
   const size = stat.size;
 
-  if (size > compare) {
+  if (!compare) {
+    const message = `Failed: Previous size of ${name} is undefined.`;
+    console.log(`${BOLD_RED}${message}${ANSI_RESET}`);
+    return 1;
+  } else if (size > compare) {
```
Comment (BeksOmega) [inline scripts/gulpfiles/test_tasks.js:172]: No need for the else when we're returning!

File: tests/scripts/update_metadata.sh [hunk 2]
```diff
@@ -12,10 +12,10 @@ readonly RELEASE_DIR='dist'
 gzip -k "${RELEASE_DIR}/blockly_compressed.js"
 gzip -k "${RELEASE_DIR}/blocks_compressed.js"
 
-blockly_size=$(wc -c < "${RELEASE_DIR}/blockly_compressed.js")
-blocks_size=$(wc -c < "${RELEASE_DIR}/blocks_compressed.js")
-blockly_gz_size=$(wc -c < "${RELEASE_DIR}/blockly_compressed.js.gz")
-blocks_gz_size=$(wc -c < "${RELEASE_DIR}/blocks_compressed.js.gz")
+blockly_size=$(wc -c < "${RELEASE_DIR}/blockly_compressed.js" | xargs)
```
Comment (BeksOmega) [inline tests/scripts/update_metadata.sh:15]: Why does `| xargs` mean whitespace gets stripped? Could  you add a comment to the source code?

**Review by BeksOmega — APPROVED** [review]

File: scripts/gulpfiles/test_tasks.js (hunk 1 above)
Comment (gonfunko) [reply scripts/gulpfiles/test_tasks.js]: Good call, done and updated the existing clause as well.

File: tests/scripts/update_metadata.sh (hunk 2 above)
Comment (gonfunko) [reply tests/scripts/update_metadata.sh]: Done.
