### PR TITLE
Procedures test workspace cleanup

### LINKED ISSUE #4080: Workspace is not always disposed in mocha tests
**Problem**

Some mocha tests make the incorrect assumption that the before/after of an outer test suite has access to objects defined on `this` from inner suites and due to this assumption, some tests do not dispose the created workspace.

Common example:
```
suite('Outer suite', function() {
  setup(function() {
    // Setup workspace that most tests use.
    this.workspace = new Workspace();
  });
  teardown(function() {
    this.workspace.dispose();
  });
  ...
  suite('Inner suite', function() {
    setup(function() {
      this.workspace.dispose(); // dispose of workspace because we're not using it
      // Create a new workspace and ASSUME it'll be cleaned up by outer suite's teardown but be WRONG
      this.workspace = new Workspace(some extra options);
    });
    ...
  });
});
```

The inner suite has a copy of the outer context, but when references are changed, then it is not reflected in the outer suite context (at teardown). In the above example, what actually happens is that the first workspace created in the outer suite is disposed of twice (once in inner suite setup, once in outer suite teardown) and the second workspace created in the inner suite is never disposed.

**Proposed solution**

Should review existing mocha tests and fix teardown so that workspaces all end up being disposed of properly. Potentially also investigate if there were any other bugs in tests due to this assumption.

**Additional context**

Chrome developer tools and breakpoints were used to confirm that this is the scenario and checking the mocha source code appears to support this as well.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Closes #4080

### Proposed Changes

- Refactors tests to generate separate tests for `procedures_callreturn` and `procedures_callnoreturn` rather than use `this.callForAllTypes`.
- Adds `try`/`finally` blocks with `workspaceTeardown` where appropriate
- Removes unnecessary `block.dispose` calls (handled in `Workspace.dispose`)
- Removes unnecessary `deleteVariable` calls (each test has its own `Workspace`)

### Reason for Changes

- Without separating logic into separate test calls, if test assert failed for `procedures_callnoreturn` (was run first) then test was not run for `procedures_callreturn. This makes it easier to debug if there is a bug specific to `procedures_callreturn` or `procedures_callnoreturn`
- Workspaces are now always disposed even if assert fails
- Removing unnecessary logic helps simplify tests

### Test Coverage

Ran mocha tests

Tested on:
* Desktop Chrome

### Documentation

n/a

### Additional Information

Behavior of tests unchanged.

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

File: tests/mocha/procedures_test.js [hunk 1]
```diff
@@ -505,7 +484,7 @@ suite('Procedures', function() {
           this.workspaceSvg.clearUndo();
           Blockly.Events.setGroup('g1');
           this.barDef.setEnabled(false);
-          Blockly.Events.setGroup(false);
+          // Blockly.Events.setGroup(false);
```
Comment (alschmiedt) [inline tests/mocha/procedures_test.js]: Can this be removed?

**Review by alschmiedt — APPROVED** [review]

File: tests/mocha/procedures_test.js (hunk 1 above)
Comment (moniika) [reply tests/mocha/procedures_test.js]: I commented this temporarily as i was debugging why a certain warning was happening.
