### PR TITLE
Removed positionNewBlock

### LINKED ISSUE #3299: BlockSvg.positionNewBlock is a dupe of BlockSvg.positionNearConnection
**Describe the bug**

There are two almost identical functions on BlockSvg.

positionNewBlock moves a block passed to the function.
positionNearConnection moves the block the function is called on.

**To Reproduce**

* [positionNewBlock](https://github.com/google/blockly/blob/af72df58aecc89e1be90dcb3ea196d9078109a53/core/block_svg.js#L1785)
* [positionNearConnection](https://github.com/google/blockly/blob/af72df58aecc89e1be90dcb3ea196d9078109a53/core/block_svg.js#L1643)

**Expected behavior**

One function.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Closes #3299 

### Proposed Changes

Removes positionNewBlock.
Makes positionNearConnection package.

### Reason for Changes

Code health.

### Test Coverage

There was only [one place](https://github.com/google/blockly/search?q=positionNewBlock&unscoped_q=positionNewBlock) this function got called, and I fixed it.

Tested insertion markers, and they work fine.

Tested on:
 * Desktop Chrome

### Documentation

N/A

### Additional Information

N/A

### CODE REVIEW

File: core/block_svg.js [hunk 1]
```diff
@@ -1680,10 +1680,11 @@ Blockly.BlockSvg.prototype.scheduleSnapAndBump = function() {
  * Position a block so that it doesn't move the target block when connected.
  * The block to position is usually either the first block in a dragged stack or
  * an insertion marker.
- * @param {!Blockly.Connection} sourceConnection The connection on the moving
- *     block's stack.
- * @param {!Blockly.Connection} targetConnection The connection that should stay
- *     stationary as this block is positioned.
+ * @param {!Blockly.RenderedConnection} sourceConnection The connection on the
+ *    moving block's stack.
```
Comment (samelhusseini) [inline core/block_svg.js]: indent with 4 spaces after @param.
