### PR TITLE
fix: Make cut/copy/paste work consistently and as expected

### LINKED ISSUE #546: Can no longer use keyboard actions on blocks in the flyout
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

At one point, we were able to use Ctrl + Enter to open the context menu on blocks in the flyout, and Ctrl + C to copy blocks in the flyout (the latter automatically closed the flyout). This is no longer case. This feels inconsistent with mouse users who can still open the context menu via right click. Copy is still not available when opening the context menu via mouse, but perhaps it should be?

### Reproduction steps

1. 
2. 
3.

### Stack trace

```shell

```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by RoboErikG**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/google/blockly-keyboard-experimentation/issues/546

This is a dependency for https://github.com/google/blockly-keyboard-experimentation/pull/556 

### Proposed Changes

Updates the preconditions for cut/copy/paste to be more aware of flyouts and to use the following criteria:
- Allow copying any blocks that could be moved, deleted, and edited once pasted (isOwn<X>able)
- Allow cutting any blocks that are currently movable and deletable (is<X>able).
- Allow pasting onto editable workspaces when there's copydata available.

### Reason for Changes

You couldn't copy a block in the toolbox and then paste it into the workspace and when paste was enabled was inconsistent.

### CODE REVIEW

File: core/shortcut_items.ts [hunk 1]
```diff
@@ -124,12 +124,48 @@ let copyCoords: Coordinate | null = null;
...
   focused: IFocusableNode,
 ): focused is ICopyable<ICopyData> & IDeletable & IDraggable {
+  if (!(focused instanceof BlockSvg)) return false;
+  return (
+    isICopyable(focused) &&
+    isIDeletable(focused) &&
+    focused.isOwnDeletable() &&
+    isDraggable(focused) &&
+    focused.isOwnMovable() &&
+    focused.isOwnEditable()
```
Comment (maribethb) [inline core/shortcut_items.ts]: Is Editable actually required? That seems like a new requirement that didn't exist before. If the block isn't editable (i.e. fields can't be changed) but it is movable and deletable, i think it should still be able to be copied (especially if we didn't have this restriction before). Was this solving a specific problem?

**Review by maribethb — COMMENTED** [review]
Generally I think this makes sense but it would be nice if there were more test cases specifically covering the kinds of blocks that weren't copyable before this and now are.

lgtm pending question about editable though.

File: core/shortcut_items.ts (hunk 1 above)
Comment (RoboErikG) [reply core/shortcut_items.ts]: Whoops. Good catch. I'll remove that check from here and isCuttable.

**Comment by maribethb** [comment]
Sorry, just merged my change so you got the merge conflict, please be sure to add the ephemeralFocusTaken check as well. Thanks!

**Review by maribethb — APPROVED** [review]

File: core/shortcut_items.ts [hunk 2]
```diff
@@ -127,6 +127,40 @@ let copyCoords: Coordinate | null = null;
...
+ *
+ * TODO(#9098): Revise these criteria.  The latter criteria prevents
+ * shadow blocks from being copied; additionally, there are likely to
+ * be other circumstances were it is desirable to allow movable /
+ * copyable copies of a currently-unmovable / -copyable block to be
+ * made.
+ *
+ * @param focused The focused object.
+ */
+function isCuttable(focused: IFocusableNode): boolean {
```
Comment (cpcallen) [inline core/shortcut_items.ts:162]: The reason I created `isCopyable`, above, was to ensure that cut and copy used _common_ criteria for deciding if something can be cut/copied, with cut being allowed for anything that can be copied and is additionally deletable—AFAICT there is no circumstance where it should be possible to cut something but _not_ copy it.

So `isCuttable` should call `isCopyable` (not just `isICopyable`), and return false if it does.  Or… we could just have the cut `preconditionFn` just check `isCopyable(focused) && focused.isDeletable()`, as it previously did.

File: core/shortcut_items.ts [hunk 3]
```diff
@@ -127,6 +127,40 @@ let copyCoords: Coordinate | null = null;
...
   focused: IFocusableNode,
 ): focused is ICopyable<ICopyData> & IDeletable & IDraggable {
+  if (!(focused instanceof BlockSvg)) return false;
+  return (
+    isICopyable(focused) &&
+    isIDeletable(focused) &&
+    focused.isOwnDeletable() &&
+    isDraggable(focused) &&
+    focused.isOwnMovable()
+  );
```
Comment (cpcallen) [inline core/shortcut_items.ts:137]: This change makes things that we decided we did not want to make copyable copyable.

This includes shadow blocks, but also blocks that have custom `isDeletable` and `isMovable` methods.

While I was working on #9084 we decided we did not want to do that in v12.

I'm not necessarily averse to making some things copyable (which were not previously copyable), but It is in my opinion a mistake to have done so without introducing an `isCopyable` method on `ICopyable` so that block definition authors can have more fine-grained control.

File: core/shortcut_items.ts [hunk 4]
```diff
@@ -151,29 +185,45 @@ export function registerCopy() {
     name: names.COPY,
     preconditionFn(workspace, scope) {
       const focused = scope.focusedNode;
+      if (!(focused instanceof BlockSvg)) return false;
```
Comment (cpcallen) [inline core/shortcut_items.ts:188]: This prevents anything except blocks—e.g., workspace comments—from being copied.

File: core/shortcut_items.ts [hunk 5]
```diff
@@ -151,29 +185,45 @@ export function registerCopy() {
...
+        ? workspace.targetWorkspace
+        : workspace;
       return (
-        !workspace.isReadOnly() &&
-        !Gesture.inProgress() &&
         !!focused &&
-        isCopyable(focused) &&
-        !getFocusManager().ephemeralFocusTaken()
+        !!targetWorkspace &&
+        !targetWorkspace.isReadOnly() &&
```
Comment (cpcallen) [inline core/shortcut_items.ts:196]: It's not clear to me that the main workspace being readonly should prevent blocks from being copied from the flyout.

(It also isn't clear to me that it should prevent blocks from being copied from the main workspace either—but that was the previous behaviour so leaving it as-is for the time being is fine.)

**Review by cpcallen — COMMENTED** [review]
There are a number of significant issues with this PR, including making a change that we had decided not to make as well as breaking copying of workspace comments.

I think it should be (mostly) reverted, and a different stab taken at making it possible to copy blocks from the workspace, by ascertaining what change had made them uncopybable and addressing that as narrowly as possible.  Further increasing the range of things that can be copied should be left until we decide we want to implement the proposed changes described in #9098 (or a comparable alternative approach).
