### PR TITLE
Fix #3228 by only using the dark path offset in Geras.

### LINKED ISSUE #3228: Geras specific code in common? Bottom row height calculation.
**Describe the bug**

Thrasos blocks' text will move when other blocks connect:
MinusOne1
MinusOne2

**To Reproduce**

1. Switch to thrasos renderer.
2. Import the following XML.
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="logic_negate" id="nka^Or2rbTADRdCNzR$v" x="45" y="49"/>
  <block type="logic_negate" id="JlPVJIl`?P!2X6k!AG9o" x="131" y="48"/>
</xml>
```
3. Connect the right block to the left block and observe the wobble.

**Expected behavior**

No wobble.

**Additional context**

I believe the problem is related to the minus 1 [here](https://github.com/google/blockly/blob/43f9ab68899fa96565a3d3d2ac131c3dce283e29/core/renderers/common/info.js#L311).

When it's commented out there's no more wobble:
MinusOne3

This also affects other renderers. For example take minimalist and remove the spacer rows:
MinusOne4
MinusOne5

You get gradually smaller blocks.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #3228 

### Proposed Changes

Only use the dark path offset in bottom row height in Geras

### Reason for Changes

Height of the connected block includes the dark path, but height while laying out this block doesn't.

### Test Coverage
Checked Geras, Thrasos, and Minimalist.  Test cases included a concatenation of not blocks and of ternary blocks.

### Documentation
None

### CODE REVIEW

File: core/renderers/geras/info.js [hunk 1]
```diff
@@ -73,6 +73,28 @@ Blockly.geras.RenderInfo.prototype.getRenderer = function() {
...
+
+  var followsStatement =
+      this.block_.inputList.length &&
+      this.block_.inputList[this.block_.inputList.length - 1]
+          .type == Blockly.NEXT_STATEMENT;
+
+  // The minimum height of the bottom row is smaller in Geras than in other
+  // renderers, because the dark path adds a pixel.
+  // If one of the row's elements has a greater height this will be overwritten
+  // inthe compute pass.
```
Comment (samelhusseini) [inline core/renderers/geras/info.js]: Nit: in the compute
