### PR TITLE
chore: Fix inadvertent block migration inconsistencies

### LINKED ISSUE #5597: Modularize blocks
Issue for tracking conversion of blocks directory to `goog.module`.

Most of the files in `blocks/` don't need to export anything, because they install blocks on the blocks object--that is, the side effects are the important thing (related to #5189).

Some files put properties on `Blockly.Constants.SomeNamespace`. These are generally not use outside of the file. They are on the constants namespace to keep them out of the global namespace. They can just become local and not exported, and it's possible that some of the leaf namespace on `Blockly.Constants` will also not be needed.

### PR DESCRIPTION
**Pull request by cpcallen**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Once #5779 has been merged, this PR…

closes #5597

### Proposed Changes

- Reinstate `goog.require`s-for-side-effects that were inadvertently  removed.
- Always use a destructuring import for `defineBlocksWithJsonArray`.
- Consistently use `CONSTANT_CASE` names for block-common objects.  (We could alternatively always use `camelCase` names, but since all the `MIXIN`s and `EXTENSIONS` remain all-uppercase this seems the more consistent.)

### Reason for Changes

Consistency.

### Test Coverage

`npm test` succeeds.

### CODE REVIEW

File: blocks/logic.js [hunk 1]
```diff
@@ -26,13 +25,14 @@ const {Mutator} = goog.require('Blockly.Mutator');
 const {RenderedConnection} = goog.requireType('Blockly.RenderedConnection');
 /* eslint-disable-next-line no-unused-vars */
 const {Workspace} = goog.requireType('Blockly.Workspace');
+const {defineBlocksWithJsonArray} = goog.require('Blockly.common');
```
Comment (rachel-fenichel) [inline blocks/logic.js:28]: Great: this was bothering me even though it wasn't hurting anything.

File: blocks/procedures.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ goog.require('Blockly.Warning');
  * Common properties for the procedure_defnoreturn and
  * procedure_defreturn blocks.
  */
-const procedureDef = {
+const PROCEDURE_DEF_COMMON = {
```
Comment (rachel-fenichel) [inline blocks/procedures.js:49]: :+1:

**Review by rachel-fenichel — APPROVED** [review]
