### PR TITLE
fix: make deserialization use the new render management system

### LINKED ISSUE #7290: Make JSON deserialization use the render queue
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

JSON Deserialization currently still uses the old immediate rendering system, because I haven't had time to clean it up yet. 

### Request

Instead it should use the render queue, so we can fully tear out the old system.

### Alternatives considered

N/A

### Additional context

I think I can get away with not updating XML by using the same immediate-render function suggested in https://github.com/google/blockly/issues/7068#issuecomment-1635099700, but I'll know more once I dig into this!

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #7290 

### Proposed Changes

Changed both the JSON and XML deserialization systems to use the render queue, but trigger an immediate render.

### Reason for Changes

Moving both sytems to use the render queue allows us to get rid of the old render management system. But I chose to make them trigger an immediate render (instead of waiting until the end of the frame) to ensure 100% backwards compatibility.

We could have people use the `finishQueuedRenders` method if they want to calculate things based on the size/position of the blocks after deserialization. However, as we discovered last time I was reorganizing stuff, that's technically a breaking change :/ And I think deserialization is a much more high-risk area for this kind of thing! (as opposed to like, adding an input to a block).

### Test Coverage

* Verified that there is no performance impact for deserialization. The spaghetti tests ran in the same amount of time before and after this change.
* Verified that copying and pasting properly renders the block.
* Verified that setting shadows programatically properly renders the block.

### Documentation

N/A

### Additional Information

N/A

Dependent on: https://github.com/google/blockly/pull/7296

### CODE REVIEW

File: core/flyout_base.ts [hunk 1]
```diff
@@ -626,8 +627,11 @@ export abstract class Flyout extends DeleteArea implements IFlyout {
     const parsedContent = toolbox.convertFlyoutDefToJsonArray(flyoutDef);
     const flyoutInfo = this.createFlyoutInfo(parsedContent);
 
+    renderManagement.triggerQueuedRenders();
```
[the remark this answers is not in the document]
Comment (maribethb) [reply core/flyout_base.ts:630]: > Would it make sense to make show async in the future

Seems reasonable.

> If so I can set this up to return a resolved promise to make it easier for folks to transition.

by "this" do you mean the `show` method? similar to my comments below, I feel like that's a bit misleading right now. also it's kind of hard to communicate that they can go ahead and wait on a promise now. if at some point we do a breaking change where we make show async, then that's when it would make the most sense to announce the change, so idk what we'd get out of adding an immeditately-resolved promise right now

File: core/icons/comment_icon.ts [hunk 2]
```diff
@@ -237,13 +237,24 @@ export class CommentIcon extends Icon implements IHasBubble, ISerializable {
     return this.bubbleVisiblity;
   }
 
-  setBubbleVisible(visible: boolean): void {
-    if (visible && (this.textBubble || this.textInputBubble)) return;
-    if (!visible && !(this.textBubble || this.textInputBubble)) return;
+  /**
+   * Sets whether the bubble is visible or not.
+   *
+   * @returns A promise that resolves when the the bubble has finished opening.
```
Comment (maribethb) [inline core/icons/comment_icon.ts:243]: This seems kind of misleading since you're not actually waiting on anything to finish. Seems like the `show*EditableBubble` methods would have to also return promises in order for this description to be accurate. Currently not sure of the value of adding these immediately-resolving promises. Is this the same thing you're proposing to do in the flyout.show method?

File: core/xml.ts [hunk 3]
```diff
@@ -545,6 +547,27 @@ export function appendDomToWorkspace(
...
+ *
+ * This is defined internally so that it doesn't trigger an immediate render,
+ * which we do want to happen for external calls.
+ *
+ * @param xmlBlock XML block element.
+ * @param workspace The workspace.
+ * @returns The root block created.
+ * @internal
+ */
+export function domToBlockInternal(
```
Comment (maribethb) [inline core/xml.ts:567]: I get why you made `domToBlock` render immediately, but I don't love this name. It's not very descriptive, and it implies external developers would never want to call it. But in reality they might be perfectly fine not triggering an immediate render. What about `domToBlockAsync`? or something better than that in the same vein? Then we don't have to mark it as internal.

Or is your plan to eventually make the breaking change to `domToBlock`? in that case i don't care quite as much if this method is intended to be temporary

**Comment by maribethb** [comment]
sorry didn't realize this was a draft

File: core/icons/comment_icon.ts (hunk 2 above)
Comment (BeksOmega) [reply core/icons/comment_icon.ts]: I removed these in the previous PR, and I'm not planning to add promises to the flyout related stuff (based on your feedback)!

File: core/xml.ts (hunk 3 above)
Comment (BeksOmega) [reply core/xml.ts:567]: My plan is indeed to eventually make the breaking change to `domToBlock` (unless there's an important reason we don't want to do that)! I chose the `domToBlockInternal` name to match the naming of the JSON serialization systsem.

**Review by maribethb — APPROVED** [review]
