### PR TITLE
fix: Focus nearest neighbor when deleting a focused block

### LINKED ISSUE #9585: Deleting a top-level selected block scrolls the workspace to the top left
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

When you delete the selected block and there is no containing parent block for the focus manager to select (ie the block is top-level), the manager defaults to focusing whatever block is in the top-left of the workspace which scrolls the workspace to top left.

This behavior is very annoying for large workspaces because it means constantly having to re-scroll to wherever you are in your project whenever you delete something. For example, if you want to delete three blocks that are top level in the bottom right of your workspace, you're going to have to scroll all the way from the top left to the bottom right three times.

The expected behavior imo would be to focus whatever node is closest to the block's original location before being dragged/deleted.

### Reproduction steps

1. Open the Blockly playground
2. Place a block in the top-left of the workspace and scroll to the right so that the block is no longer visible
3. Place a few other blocks on the workspace
4. Delete one of these blocks
5. Watch as the workspace is scrolled away from where you were working

See screenshots below for a recording of me reproducing this issue

### Priority

This is primarily an issue for our MakeCode Arcade editor, where large blocks projects are very common. I expect this will affect most of our users, so we consider this a high priority issue.

I haven't worked in the focus manager code before, so I can't speak to the effort involved but the solution at least seems clear.

### Stack trace

```shell

```

### Screenshots

Image

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9585

### Proposed Changes
This PR adjusts the focus behavior when a focused block is deleted. Previously, deleting a focused block would focus the workspace, which would in turn focus the first (left/topmost)  block on the workspace. This could cause large jumps in scroll position. Now, when a focused block is deleted, it moves focus to the closest remaining block, resulting in a smaller (or no) workspace movement.

The tests were partially LLM-generated in response to a list of testcases I specified. I reviewed, modified them, and manually added an additional testcase.

### CODE REVIEW

File: packages/blockly/core/block_svg.ts [hunk 1]
```diff
@@ -904,7 +930,12 @@ export class BlockSvg
       if (parent) {
         focusManager.focusNode(parent);
       } else {
-        setTimeout(() => focusManager.focusTree(this.workspace), 0);
+        const nearestNeighbour = this.getNearestNeighbour();
+        if (nearestNeighbour) {
+          setTimeout(() => focusManager.focusNode(nearestNeighbour), 0);
```
Comment (BenHenning) [inline packages/blockly/core/block_svg.ts]: Is there any case where there may be a sequence of deletions such that this triggers an attempt to focus the next closest node before it's deleted? Might be worth adding a test case to see if that's actually possible and, if so, make this a bit more robust against that.

File: packages/blockly/tests/mocha/block_test.js [hunk 2]
```diff
@@ -2946,4 +2946,94 @@ suite('Blocks', function () {
...
+      this.workspace = Blockly.inject('blocklyDiv');
+      const firstBlock = this.workspace.newBlock('stack_block');
+      firstBlock.moveBy(-500, -500);
+    });
+
+    test('Deleting the sole block on the workspace focuses the workspace', function () {
+      const block = this.workspace.getTopBlocks(false)[0];
+      Blockly.getFocusManager().focusNode(block);
+      block.dispose();
+      this.clock.runAll();
```
Comment (BenHenning) [inline packages/blockly/tests/mocha/block_test.js:2961]: Is this actually needed here & below?

File: packages/blockly/tests/mocha/block_test.js [hunk 3]
```diff
@@ -2946,4 +2946,94 @@ suite('Blocks', function () {
...
+      );
+    });
+
+    test('Bulk deleting blocks does not focus another dying block', function () {
+      for (let i = 0; i < 50; i++) {
+        this.workspace.newBlock('stack_block');
+      }
+
+      Blockly.getFocusManager().focusNode(
+        this.workspace.getTopBlocks(false)[0],
```
Comment (BenHenning) [inline packages/blockly/tests/mocha/block_test.js]: This relates to my other comment: perhaps double check that the nearest neighbor is still actually doing what it seems like and selecting and trying to focus a block before it's disposed. It may be the case that something else (maybe the focus system or another part of disposal) is robust against this failure case.

File: packages/blockly/tests/mocha/block_test.js [hunk 4]
```diff
@@ -2946,4 +2946,94 @@ suite('Blocks', function () {
...
+      const focused = Blockly.getFocusManager().getFocusedNode();
+      assert.equal(
+        focused,
+        blockRight,
+        'Focus should move to the closest remaining block (blockRight at (100, 0))',
+      );
+    });
+
+    test('Bulk deleting blocks does not focus another dying block', function () {
+      for (let i = 0; i < 50; i++) {
```
Comment (BenHenning) [inline packages/blockly/tests/mocha/block_test.js]: Idea can probably be tested with fewer blocks (for perforamnce). Maybe just have something like 5?

File: packages/blockly/tests/mocha/block_test.js [hunk 5]
```diff
@@ -2946,4 +2946,94 @@ suite('Blocks', function () {
...
+    test('Deleting an unfocused block does not change focus', function () {
+      const a = this.workspace.getTopBlocks(false)[0];
+      const b = this.workspace.newBlock('stack_block');
+      this.workspace.newBlock('stack_block');
+
+      Blockly.getFocusManager().focusNode(a);
+      b.dispose();
+      this.clock.runAll();
+
+      assert.equal(
```
Comment (BenHenning) [inline packages/blockly/tests/mocha/block_test.js]: Here & elsewhere: I suggest using `strictEqual` instead since there can be problems with the deep equal for connected blocks (circular references are possible), and it shouldn't actually be necessary for verifying focus.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @gonfunko! Largely LGTM but had a few thoughts--PTAL.

File: packages/blockly/core/block_svg.ts (hunk 1 above)
Comment (gonfunko) [reply packages/blockly/core/block_svg.ts]: That is a possibility, and is why `getNearestNeighbour()` filters the blocks by `isDeadOrDying()`, so that it only returns a block that isn't about to be disposed of. This is also the purpose of the test that makes 50 blocks and clears the workspace.

File: packages/blockly/tests/mocha/block_test.js (hunk 2 above)
Comment (gonfunko) [reply packages/blockly/tests/mocha/block_test.js:2961]: Yes, this test file mocks the clock and this gets the various async focus things to happen.

File: packages/blockly/tests/mocha/block_test.js (hunk 5 above)
Comment (gonfunko) [reply packages/blockly/tests/mocha/block_test.js]: Oh nice, that's a big improvement. We should probably take a pass to update all the tests to do this where relevant to avoid locking things up when there's a failure.

File: packages/blockly/tests/mocha/block_test.js (hunk 4 above)
Comment (gonfunko) [reply packages/blockly/tests/mocha/block_test.js]: Done

File: packages/blockly/tests/mocha/block_test.js (hunk 3 above)
Comment (gonfunko) [reply packages/blockly/tests/mocha/block_test.js]: Adjusted this is a bit to verify that it does not focus dying blocks.

**Comment by gonfunko** [comment]
This also fixes #9601

**Review by BenHenning — APPROVED** [review]
Thanks @gonfunko!
