### PR TITLE
Fix failing svg canvas test

### LINKED ISSUE #1976: workspace_svg_test is broken and doesn't seem to be run by Travis
### Problem statement

Travis doesn't seem to open tests/workspace_svg/index.html as one of the tests is currently broken.

### Expected Behavior

Test runs and passes.

### Actual Behavior

One of the tests throws an error when it tries to dispose of a block.

### Steps to Reproduce

Open tests/workspace_svg/index.html

Check the console

### Stack Traces

TypeError: Cannot read property 'removeChild' of null
    at Blockly.BlockSvg.dispose (block_svg.js:851)
    at test_flatWorkspace (workspace_svg_test.js:73)
    at goog.testing.TestCase.invokeFunction_ (testcase.js:907)
    at goog.testing.TestCase.safeRunTest_ (testcase.js:837)
    at Function.goog.testing.Continuation_.run (testcase.js:2057)
    at goog.testing.TestCase.<anonymous> (testcase.js:750)
    at Function.goog.testing.Continuation_.run (testcase.js:2057)
    at goog.testing.TestCase.<anonymous> (testcase.js:741)
    at new goog.Promise (promise.js:172)
    at goog.testing.TestCase.runTestsReturningPromise (testcase.js:740)
    at goog.testing.TestRunner.execute (testrunner.js:329)
    at jsunit.js:191

### Operating System and Browser

Desktop Chrome

### PR DESCRIPTION
**Pull request by RoboErikG**
Partial fix for #1976. This fixes the broken test by initializing the
svg for blocks when they're created.

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Partially fixes #1976 . It fixes the broken test, but doesn't make Travis run these additional tests.

### Test Coverage

Tested on:
Desktop Chrome

### Additional Information

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/1977)

### CODE REVIEW

File: tests/workspace_svg/workspace_svg_test.js [hunk 1]
```diff
@@ -24,6 +24,12 @@ function helper_createWorkspaceWithToolbox() {
   return Blockly.inject('blocklyDiv', {toolbox: toolbox});
 }
 
+function helper_createNewBlock(workspace, type) {
+  var block = workspace.newBlock(type);
+  block.initSvg();
```
Comment (AnmAtAnm) [inline tests/workspace_svg/workspace_svg_test.js]: Where does this get called outside of testing? Should WorkspaceSvg.newBlock() override Workspace.newBlock() to provide this functionality?

Comment (RoboErikG) [reply tests/workspace_svg/workspace_svg_test.js]: It gets called all over the code base. It might make sense to do a cleanup and move it into BlockSvg's constructor, but I'm not sure if there would be side effects.

Comment (AnmAtAnm) [reply tests/workspace_svg/workspace_svg_test.js]: I've added #1980 to to track this issue.

Comment (rachel-fenichel) [reply tests/workspace_svg/workspace_svg_test.js]: Alllll over the place.  I've chatted with Neil about this and we agree that it's worth cleaning up eventually, but carefully.

Recall that Blockly did not originally have a headless mode.  When creating the headless mode, Neil pulled out some common code and had one XML helper function call the other.  The rendered version then goes through after the fact and does some additional work to put everything in order.  The main problem is that deserializing a block may actually create multiple blocks down the stack, and the information flow doesn't really reflect that.  

The solution is probably to completely separate the code for deserializing rendered and non-rendered blocks, which will then let us do less post-facto messing around to get SVG initialization right.  The comment serialization/deserialization stuff has a similar issue.
