### PR TITLE
fix: Always draw dragged blocks atop others in the workspace.

### LINKED ISSUE #6852: Dragged blocks appear behind blocks in the workspace
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you drag a block from the flyout, or drag blocks on the workspace, they appear behind other blocks, when they should be on top.

### Reproduction steps

1. Drag a block from the flyout
2. Drag another block from the flyout
3. Observe how the second block is rendered behind the first block.

### Stack trace

```shell
N/A
```

### Screenshots

[Screen recording 2023-02-16 10.36.51 AM.webm](https://user-images.githubusercontent.com/25440652/219457133-b8ade7b3-2b9a-47ab-86cb-28cfe450c1e7.webm)

### Browsers

_No response_

### Additional Info

Does not reproduce on master. I'm assuming this is related to #6758

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #6852

### Proposed Changes
When blocks are dragged, bring them to the front, and update `setParent` to insert blocks before the block being dragged, if any, when removing it from its parent.

#### Behavior Before Change
Blocks would occassionally appear behind other blocks when being dragged.

#### Behavior After Change
Blocks being dragged appear atop all other blocks.

### Reason for Changes
Fixes a regression introduced in #6758.

### CODE REVIEW

**Comment by BeksOmega** [comment]
This no longer applies because #6758 was reverted

**Comment by BeksOmega** [comment]
#6758 was rerolled as https://github.com/google/blockly/pull/7070 so we need to merge this now as well.

**Review by BeksOmega — APPROVED** [review]

File: core/block_svg.ts [hunk 1]
```diff
@@ -328,7 +328,14 @@ export class BlockSvg
     } else if (oldParent) {
       // If we are losing a parent, we want to move our DOM element to the
       // root of the workspace.
-      this.workspace.getCanvas().appendChild(svgRoot);
+      const draggingBlock = this.workspace
+        .getCanvas()
+        .querySelector('.blocklyDragging');
+      if (draggingBlock) {
+        this.workspace.getCanvas().insertBefore(svgRoot, draggingBlock);
```
Comment (BeksOmega) [inline core/block_svg.ts:335]: @gonfunko do you remember what case this was handling?

Comment (gonfunko) [reply core/block_svg.ts:335]: Not offhand :/ Judging by the comment maybe it's when a block is disconnected from a stack?
