### PR TITLE
Fix: Remove the collapsed block warning when expanding a block

### LINKED ISSUE #6020: Warnings for collapsed blocks does not update
**Describe the bug**
When you collapse a block and a child block has a warning we display a warning message on the block. This message isn't getting updated when the block is expanded.

**To Reproduce**

1. Go to the playground

2. Load the following xml
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_repeat_ext" id="?[R7O,[bcA,gyUuru9ji" x="62" y="63">
    <value name="TIMES">
      <shadow type="math_number" id="]sg4g$S5/$djRL^,HUBv">
        <field name="NUM">10</field>
      </shadow>
    </value>
    <statement name="DO">
      <block type="procedures_ifreturn" id="-*QyH~ToOCmVL#0E1ew@" disabled="true">
        <mutation value="1"></mutation>
      </block>
    </statement>
  </block>
</xml>
```
4. Collapse the parent block
5. Expand the parent block
6. See how the error message still exists even when the block is expanded

**Expected behavior**

**Screenshots**
Screen Shot 2022-03-22 at 2 07 45 PM

**Additional context**

### PR DESCRIPTION
**Pull request by RoboErikG**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #6020 

### Proposed Changes

- Clears the collapsed block warning message when a block is expanded.
- When collapsing, checks if any children have a warning and if so adds the collapsed warnings warning.

### Reason for Changes

The collapsed block warning message was set if any block in a collapsed stack added a warning, but wasn't added if there already was a warning and was never removed making it sticky on the parent even after expanding and deleting the block with the warning.

### CODE REVIEW

**Review by rachel-fenichel — COMMENTED** [review]
Code looks fine, but please check if we have any related tests and add one for this case if possible.

**Comment by RoboErikG** [comment]
Added tests, which required fixing the other bug where warning icons didn't show up right away when a block is collapsed.

File: core/block_svg.ts [hunk 1]
```diff
@@ -507,6 +507,23 @@ export class BlockSvg
...
 
+  /**
+   * Traverses child blocks to see if any of them have a warning.
+   *
+   * @returns true if any child has a warning, false otherwise.
+   */
+  private childHasWarning(): boolean {
+    const children = this.getChildren(false);
+    for (const child of children) {
+      if (child.getIcon(WarningIcon.TYPE)) {
```
Comment (rachel-fenichel) [inline core/block_svg.ts:518]: Can be combined into `if (child.getIcon(WarningIcon.TYPE) || child.childHasWarning()) return true;`

**Review by rachel-fenichel — COMMENTED** [review]
One quick change then lgtm. I'll manually add the pr: fix label in a sec.

**Review by rachel-fenichel — APPROVED** [review]
