### PR TITLE
Cursor rtl

### LINKED ISSUE #3024: Keyboard Nav: Cursor in RTL not working
**Describe the bug**
Cursor is not getting rendered correctly for RTL. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### LINKED ISSUE #3028: Keyboard Nav: Cursor not showing correct location
**Describe the bug**
The cursor doesn't seem to be showing the correct location on the workspace.

**To Reproduce**
Move cursor to the workspace. 
Insert block from flyout. 
Observe the block is moved to a slightly different location.
**Expected behavior**
Block is moved to the location of the cursor.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
Fixes #3024.
Fixes #3028
### Proposed Changes
1. Fix rtl for the cursor. 
2. Set the cursorSvg parent on the workspace to the svgBlockCanvas_. This allows the user to drag around the workspace and the cursor sticks to the workspace. Also this is what was messing up inserting to the wrong spot.

### Test Coverage

Tested on:

### CODE REVIEW

File: core/keyboard_nav/cursor_svg.js [hunk 1]
```diff
@@ -321,13 +322,17 @@ Blockly.CursorSvg.prototype.showWithStack_ = function(curNode) {
...
   // Shift the rectangle slightly to upper left so padding is equal on all sides.
-  var x = -1 * Blockly.CursorSvg.STACK_PADDING / 2;
-  var y = -1 * Blockly.CursorSvg.STACK_PADDING / 2;
+  var xPadding = -1 * Blockly.CursorSvg.STACK_PADDING / 2;
+  var yPadding = -1 * Blockly.CursorSvg.STACK_PADDING / 2;
 
-  this.currentCursorSvg = this.cursorSvgRect_;
-  this.setParent_(block);
+  var x = xPadding;
+  var y = yPadding;
```
Comment (samelhusseini) [inline core/keyboard_nav/cursor_svg.js]: Do you need yPadding?

File: core/keyboard_nav/cursor_svg.js [hunk 2]
```diff
@@ -439,6 +460,15 @@ Blockly.CursorSvg.prototype.positionRect_ = function(x, y, width, height) {
   this.cursorSvgRect_.setAttribute('y', y);
   this.cursorSvgRect_.setAttribute('width', width);
   this.cursorSvgRect_.setAttribute('height', height);
+  this.currentCursorSvg = this.cursorSvgRect_;
+};
+
+/**
+ * Flip the SVG paths in RTL.
+ * @param {SVGElement} cursor The cursor that we want to flip.
+ */
```
Comment (samelhusseini) [inline core/keyboard_nav/cursor_svg.js]: add visibility.

File: core/keyboard_nav/cursor_svg.js [hunk 3]
```diff
@@ -439,6 +460,15 @@ Blockly.CursorSvg.prototype.positionRect_ = function(x, y, width, height) {
   this.cursorSvgRect_.setAttribute('y', y);
   this.cursorSvgRect_.setAttribute('width', width);
   this.cursorSvgRect_.setAttribute('height', height);
+  this.currentCursorSvg = this.cursorSvgRect_;
+};
+
+/**
+ * Flip the SVG paths in RTL.
+ * @param {SVGElement} cursor The cursor that we want to flip.
```
Comment (samelhusseini) [inline core/keyboard_nav/cursor_svg.js]: !SVGElement, since you don't check for null when setting the attribute.
