### PR TITLE
fix(build): support running Blocky locally on Windows machines

### LINKED ISSUE #6864: Errors when building on Windows (unable to identify chunk)
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Running 'npm run start' produced the following error on Windows:

> blockly@9.2.1 start
> npm run build && concurrently -n tsc,server "tsc --watch --preserveWatchOutput --outDir 'build/src' --declarationDir 'build/declarations'" "http-server ./ -s -o /tests/playground.html -c-1"

> blockly@9.2.1 build
> gulp build

[22:52:24] Using gulpfile ~\Documents\GitHub\blockly\gulpfile.js
[22:52:24] Starting 'build'...
[22:52:24] Starting 'buildLangfiles'...
[22:52:24] Finished 'buildLangfiles' after 411 ms
[22:52:24] Starting 'buildJavaScript'...
Unquoted enums in 0 files.
[22:52:34] Finished 'buildJavaScript' after 9.85 s
[22:52:34] Starting 'buildDeps'...
[22:52:38] Finished 'buildDeps' after 3.48 s
[22:52:38] Starting 'buildCompiled'...
[22:52:41] 'buildCompiled' errored after 2.76 s
[22:52:41] Error: Unable to identify chunk
    at C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:573:23
    at Array.map (<anonymous>)
    at getChunkOptions (C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:558:38)
    at buildCompiled (C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:646:24)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (C:\Users\perny\Documents\GitHub\blockly\node_modules\bach\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[22:52:41] 'build' errored after 17 s

Looking a little closer on the error, I was able to find the problem.
The chunk.entry had a windows separator (backslash) instead of the slash '/'. This was easy to fix by this thing:
 // Convert windows path separators into '/' so that the entrypoint lookup works as intended
    const chunkEntries = chunks.map(chunk => chunk.entry.replace(/\\/g, '/'));

    // Figure out which chunk this is by looking for one of the
    // known chunk entrypoints in chunkFiles.  N.B.: O(n*m).  :-(
    const chunk = chunks.find(
        (chunk, index) => chunkFiles.find(f => f.endsWith('/' + chunkEntries[index])));

I thought it would be nice to make a PR as well, but it turned out that 1334 files had been modified newlines CRLF, so this was a no go.

### Reproduction steps

1. run 'npm run start' on a Windows system

### Stack trace

```shell
[22:52:41] Error: Unable to identify chunk
    at C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:573:23
    at Array.map (<anonymous>)
    at getChunkOptions (C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:558:38)
    at buildCompiled (C:\Users\perny\Documents\GitHub\blockly\scripts\gulpfiles\build_tasks.js:646:24)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (C:\Users\perny\Documents\GitHub\blockly\node_modules\bach\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by abdul-alhasany**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves
#6864 and #7097 

Fixes 

### Proposed Changes
Make building process compatible with machines run on windows. 

#### Behavior Before Change
When running `npm run start` errors occur as described in the bug reports above.

#### Behavior After Change
Running `npm run start` is working with no errors on Windows.

### Reason for Changes
Help developers who work on Windows machines to run blocky locally and potentially contribute to the codebase.

### Test Coverage
I did not create any tests. I tested the code on my Windows machine. 

### Documentation
I don't think any further documentation required for this change. Current documentation already asks users to run `npm run start`. The user does not need to do anything specific on Windows machines.

### Additional Information
No

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
This looks right to me and tests pass. @cpcallen can you double-check the chunking command in the last file?

File: scripts/gulpfiles/build_tasks.js [hunk 1]
```diff
@@ -559,7 +563,10 @@ function getChunkOptions() {
     // Figure out which chunk this is by looking for one of the
     // known chunk entrypoints in chunkFiles.  N.B.: O(n*m).  :-(
     const chunk = chunks.find(
-        chunk => chunkFiles.find(f => f.endsWith(path.sep + chunk.entry)));
+        chunk => chunkFiles.find(f => {
+          return f.endsWith(path.sep.replace("\\", "/") + chunk.entry.replaceAll("\\", "/"));
+        }
+        ));
```
Comment (cpcallen) [inline scripts/gulpfiles/build_tasks.js:569]: What I'm unclear about—and what would be very helpful if you could give us some information about—is what the strings in the `chunkFiles` array look like.

On macOS (and Linux etc.) they use `/` as a separator, and I was expecting that they would use `\` on win32, and so using `f.endsWith(path.sep + chunk.entry)` (where `chunk.entry` also uses `path.sep`) should work fine.

But from this proposed code change it seems that for `chunkFiles` uses `/` as a path separator even on Windows.  Is that correct?

In any case, the proposed change can be simplified somewhat, since `path.sep` is only ever either `'/'` or `'\\'`:

```suggestion
        chunk => chunkFiles.find(f => f.endsWith('/' + chunk.entry.replaceAll("\\", "/")));
```

**Review by cpcallen — CHANGES_REQUESTED** [review]
Hi @abdul-alhasany!  Thanks for this pull request.  We especially appreciate external developers who use Windows helping us with issues like this because we've not had any frequent Windows users on the core Blockly team for some time.  I'm only sorry that I didn't have time to look at it until now.

Do have a look at my comments, questions and suggested changes below, and let me know if there is anything that is not clear.

File: scripts/gulpfiles/build_tasks.js [hunk 2]
```diff
@@ -15,6 +15,7 @@ gulp.sourcemaps = require('gulp-sourcemaps');
 
 const path = require('path');
 const fs = require('fs');
+const os = require('os');
```
[the remark this answers is not in the document]
Comment (abdul-alhasany) [reply scripts/gulpfiles/build_tasks.js:18]: Initially I wanted to use `process.platform` but it seems that os.platform is slightly [more reliable](https://stackoverflow.com/a/61744810/529024). since `os` is a native module I thought it should effect the size or the performance of the build. I am happy to change it if that is no the case.

File: scripts/gulpfiles/build_tasks.js (hunk 1 above)
Comment (abdul-alhasany) [reply scripts/gulpfiles/build_tasks.js:569]: Windows accepts both `\` and `/` which is why, in my projects, I generally opt in for `path.replaceAll("\\", "/")` to make the behavior consistent across os systems. The reason I also did not replace `path.sep` is because I did not want to introduce extra changes. I wanted to keep the original code the same as much as possible.

There are all chunk entries that pass the condition (f.endsWith):
```
build\src\core\main.js
build\src\blocks\blocks.js
build\src\generators\javascript.js
build\src\generators\python.js
build\src\generators\php.js
build\src\generators\lua.js
build\src\generators\dart.js
```

File: scripts/gulpfiles/build_tasks.js [hunk 3]
```diff
@@ -379,8 +380,9 @@ error message above, try running:
  * msg/messages.js.
  */
 function generateMessages(done) {
+  const pythonCmd = os.platform() === 'win32' ? 'python' : 'python3';
```
[the remark this answers is not in the document]
Comment (abdul-alhasany) [reply scripts/gulpfiles/build_tasks.js:383]: Sure. I can update the code.

**Review by cpcallen — CHANGES_REQUESTED** [review]
Please run `npm run format` to fix formatting issues.

**Comment by abdul-alhasany** [comment]
`build_task.js` is ignored by .eslintignore. What formatting issues are there? I can do it manually if it is required.

File: scripts/gulpfiles/build_tasks.js [hunk 4]
```diff
@@ -559,7 +567,10 @@ function getChunkOptions() {
     // Figure out which chunk this is by looking for one of the
     // known chunk entrypoints in chunkFiles.  N.B.: O(n*m).  :-(
     const chunk = chunks.find(
-        chunk => chunkFiles.find(f => f.endsWith(path.sep + chunk.entry)));
+        chunk => chunkFiles.find(f => {
+          return f.endsWith("/" + chunk.entry.replaceAll("\\", "/"));
```
Comment (cpcallen) [inline scripts/gulpfiles/build_tasks.js:571]:
```suggestion
          return f.endsWith('/' + chunk.entry.replaceAll('\\', '/'));
```

**Comment by cpcallen** [comment]
> `build_task.js` is ignored by .eslintignore. What formatting issues are there? I can do it manually if it is required.

Our lint checks are configured specifically not to do formatting checks, which are done by a separate GitHub workflow (action).  I thought I had seen a format check failure due to the double quotes, but apparently either I was mistaken or the failure was transitory, as I see it is now passing.

Nevertheless, please fix quoting as noted.

**Review by cpcallen — APPROVED** [review]
