### PR TITLE
Add checks to WorkspaceSvg dispose and fix shared Workspace tests

### LINKED ISSUE #4091: Error calling dispose on non-injected WorkspaceSvg
**Describe the bug**

Cannot safely call `dispose` on a `Blockly.WorkspaceSvg` that has not been injected.

**To Reproduce**

1. Go to playground.
2. Input the following code into the console:
```
var ws = new Blockly.WorkspaceSvg(new Blockly.Options({}));
ws.dispose();
```
3. See error

**Expected behavior**

Should be able to call `dispose` without error.

**Stack Traces**

```
Uncaught TypeError: Cannot read property 'dispose' of null
    at Blockly.MarkerManager.dispose (marker_manager.js:179)
    at Blockly.WorkspaceSvg.dispose (workspace_svg.js:821)
    at <anonymous>:1:4
```

**Additional context**

Uncovered while writing tests.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #4091
Part of #4080

### Proposed Changes

- Adds checks that prevent errors when `dispose` is called on `WorkspaceSvg` before dom is created
- Adds test for `dispose` call on `WorkspaceSvg` without `inject` or `createDom` call
- Changes workspace `dispose` calls to use `workspaceTeardown`
- Adds checks in shared workspace test to create `WorkspaceSvg` if main workspace is rendered

### Reason for Changes

- Preventing errors in `dispose` call seems reasonable and cleans up errors logged by tests
- Using `workspaceTeardown` instead of calling dispose directly prevents possibility of `dispose` call errors masking errors from test assertions
- Updating shared tests ensures that we are testing `WorkspaceSvg` when `testAWorkspace` is called for `WorkspaceSvg` tests

### Test Coverage

Ran mocha tests

Tested on:
 * Desktop Chrome

### Additional Information

Shared test cleanup depends on fix for `WorkspaceSvg` `dispose` call because test "Workspace base class getById after dispose" would otherwise fail.

### CODE REVIEW

File: tests/mocha/workspace_test.js [hunk 1]
```diff
@@ -247,7 +247,9 @@ function testAWorkspace() {
 
   suite('addTopBlock', function() {
     setup(function() {
-      this.targetWorkspace = new Blockly.Workspace();
+      this.targetWorkspace = this.workspace.rendered ?
```
Comment (rachel-fenichel) [inline tests/mocha/workspace_test.js:250]: When would the workspace not be a workspace svg, if it's a flyout?

Comment (moniika) [reply tests/mocha/workspace_test.js:250]: I suppose in headless it might not make sense to test flyout. Is that the case?
I could instead:

- Move this to WorkspaceSvg tests 
- OR do something like:

```
this.targetWorkspace = this.workspace.rendered ? this.workspace : new Blockly.Workspace();
if (this.workspace.rendered) {
  this.workspace.isFlyout = true;
  this.workspace.targetWorkspace = this.targetWorkspace;
}
```

Comment (rachel-fenichel) [reply tests/mocha/workspace_test.js:250]: Moving it to workspace_svg sounds most reasonable to me.

Comment (moniika) [reply tests/mocha/workspace_test.js]: Done.
