### PR TITLE
Fix disposing of a workspace

### LINKED ISSUE #3957: Disposing of a workspace while a mutator is open causes a crash
**Describe the bug**

Disposing of a workspace while a mutator is open causes a crash

**To Reproduce**

1. Go to the playground
2. Drag an controls_if block.
3. Open the mutator.
4. In a console, call Blockly.mainWorkspace.dispose();
5. See error

**Expected behavior**

No crash.

**Stack Traces**

```
theme_manager.js:172 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Blockly.ThemeManager.unsubscribe (theme_manager.js:172)
    at Blockly.Scrollbar.dispose (scrollbar.js:349)
    at Blockly.VerticalFlyout.Blockly.Flyout.dispose (flyout_base.js:305)
    at Blockly.WorkspaceSvg.dispose (workspace_svg.js:792)
    at Blockly.Mutator.setVisible (mutator.js:338)
    at Blockly.Mutator.Blockly.Icon.dispose (icon.js:95)
    at Blockly.Mutator.dispose (mutator.js:446)
    at Blockly.BlockSvg.dispose (block_svg.js:984)
    at Blockly.WorkspaceSvg.Blockly.Workspace.clear (workspace.js:351)
```

**Additional context**

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
Fixes #3957
Removes an extra workspace fire I previously left in

### Proposed Changes
Move deleting the theme manager after all the blocks are disposed of. 

### Test Coverage

Tested on:

### CODE REVIEW

File: core/gesture.js [hunk 1]
```diff
@@ -651,9 +651,6 @@ Blockly.Gesture.prototype.handleWsStart = function(e, ws) {
   this.setStartWorkspace_(ws);
   this.mostRecentEvent_ = e;
   this.doStart(e);
-  if (!this.startBlock_ && !this.startBubble_) {
-    this.fireWorkspaceClick_(ws);
-  }
```
Comment (moniika) [inline core/gesture.js:656]: This is on purpose right? in response to comments on #3956?

Comment (alschmiedt) [reply core/gesture.js:656]: Yup! I left it in so just removing
