### PR TITLE
fix: delete area animation

### LINKED ISSUE #8098: Delete animation and sound don't play when dragging blocks to a delete area.
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Dragging a block to the trash or the toolbar deletes the block, but does not play the delete sound.  This is a regression in V11, it works properly on V10.  All browsers.

### Reproduction steps

1. Drag a block to the trash.

### Stack trace

_No response_

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [ ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #8098 

### Proposed Changes

Hacks some things around to get delete animations to work. Everything should be internal. Please check!

### Documentation

Once we add an animation API we'll need to add those side effect requirements to the dragger docs.

### CODE REVIEW

File: core/layer_manager.ts [hunk 1]
```diff
@@ -48,6 +51,35 @@ export class LayerManager {
     return dom.createSvgElement(Svg.G, {}, svg);
   }
 
+  private createAnimationLayer(injectionDiv: Element) {
```
Comment (cpcallen) [inline core/layer_manager.ts:54]: Please provide a suitable JSDoc for this (even if it's just an excerpt of the one from `appendToAnimationLayer`).

**Review by cpcallen — APPROVED** [review]

File: core/layer_manager.ts (hunk 1 above)
Comment (BeksOmega) [reply core/layer_manager.ts:54]: This is private so it doesn't need JSDoc. I think the method signature makes it pretty clear what it's doing.
