### PR TITLE
fix: Don't include count of inputs in block ARIA label

### LINKED ISSUE #9491: Don't include the number of inputs in block ARIA labels
Currently, the number of inputs is included in blocks' ARIA labels. Instead, the label should simply note that the block "has inputs" if it does, and not include a count.

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9491

### Proposed Changes
This PR removes the count of input blocks from blocks' ARIA labels, and instead notes simply "has inputs" if that is the case.

### CODE REVIEW

File: core/block_svg.ts [hunk 1]
```diff
@@ -244,9 +244,12 @@ export class BlockSvg
...
   private computeAriaLabel(): string {
     const {blockSummary, inputCount} = buildBlockSummary(this);
-    const inputSummary = inputCount
-      ? ` ${inputCount} ${inputCount > 1 ? 'inputs' : 'input'}`
-      : '';
+    let inputSummary = '';
+    if (inputCount > 1) {
+      inputSummary = 'has inputs';
+    } else if (inputCount === 1) {
+      inputSummary = 'has input';
```
Comment (maribethb) [inline core/block_svg.ts:251]: we are going to be sad later because we don't support plural translations :/

(no action needed, this is just me wishing we had more robust i18n systems)

**Review by maribethb — APPROVED** [review]

File: core/block_svg.ts (hunk 1 above)
Comment (gonfunko) [reply core/block_svg.ts:251]: I am already sad :( But yeah, that would be good to address at some point.
