### PR TITLE
Set theme fix

### LINKED ISSUE #2331: Blockly.setTheme errors out if Blockly.getMainWorkspace() does not return a value
### Problem statement

Blockly.setTheme errors out if Blockly.getMainWorkspace() does not return a value. (This can occur if using Blockly.setTheme with no workspace yet opened, such as when attempting to initialize Blockly information before injecting code.)

### Expected Behavior

If there is no main workspace yet,  Blockly.setTheme should just set Blockly.theme_ and move on.

### Actual Behavior

Blockly.setTheme errors out with "cannot read property getAllBlocks of undefined".

### Steps to Reproduce

Load up Blockly in any playground and attempt to call Blockly.setTheme before initializing the workspace.

### Operating System and Browser

* Desktop Chrome

(I expect it applies to all of them, though.)

### Additional Information

This is a less common use case, but certainly not an unthinkable one; I ran into it earlier today while adding Blockly.setTheme in order to update a nodejs Blockly project we've been using so as not to cause the blocks to error out when loaded up.

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
#2331 

### Proposed Changes
Check for a workspace before trying to refresh the theme on all the blocks and categories in the workspace.

### Reason for Changes
Blockly.setTheme was throwing an error when the workspace had not yet been created.

### Test Coverage
Tested on:
 Desktop Chrome

### CODE REVIEW

File: core/blockly.js [hunk 1]
```diff
@@ -690,6 +690,16 @@ Blockly.setTheme = function(theme) {
...
 
+  if (ws) {
+    this.refreshTheme_(ws);
+  }
+};
+
+/**
+ * Refresh the theme for all items on the workspace.
+ * @param {Blockly.Workspace} ws Blockly workspace to refresh theme on.
+ */
```
Comment (RoboErikG) [inline core/blockly.js]: missing private annotation
