### PR TITLE
fix: Don't open the toolbox when clicking beneath the categories

### LINKED ISSUE #9198: Toolbox opens when clicking below all categories first time
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

If you click below the categories within the toolbox, the toolbox opens with the first category selected. This only happens the first time (if you click again, it closes the toolbox, and if you click a third time, nothing happens).

### Reproduction steps

1. Click in toolbox below all the categories and the toolbox opens with the first category selected

### Stack trace

```shell

```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9198

### Proposed Changes
This PR fixes a bug where clicking in the toolbox below the list of categories would cause the flyout to open with the first toolbox category selected. That behavior is preserved when the toolbox is focused via the keyboard. If the flyout is open, clicking in the toolbox below the list of categories will still dismiss it, as will clicking the selected category.

### CODE REVIEW

File: core/toolbox/toolbox.ts [hunk 1]
```diff
@@ -1134,7 +1148,7 @@ export class Toolbox
   ): void {
     if (node !== this) {
       // Only select the item if it isn't already selected so as to not toggle.
```
Comment (rachel-fenichel) [inline core/toolbox/toolbox.ts:1150]: Update the comment to explain the new clause.

**Review by BenHenning — COMMENTED** [review]
Might it be possible to add a test to verify the behavior?

File: core/toolbox/toolbox.ts (hunk 1 above)
Comment (gonfunko) [reply core/toolbox/toolbox.ts:1150]: Done.

**Comment by gonfunko** [comment]
Added a test as well.

**Review by rachel-fenichel — APPROVED** [review]
