### PR TITLE
fix: toString performance

### LINKED ISSUE #4229: Collapsed block performance
**Describe the bug**

Hidden child blocks of collapsed blocks are being re-rendered when a block is being dragged to connect to it.
This causes unnecessary performance issues.

**To Reproduce**

1. Go to the Blockly playground, and use the Spaghetti option to add a long list of connected blocks to the playground.
2. Click on each of the top level if statements and collapse them.
3. Drag another block and attempt to place it in between these blocks.
4. Notice the lag.

**Expected behavior**

Even though there aren't that many visible blocks, we are still re-rendering the block and all of it's (hidden) children as we drag a block to connect to it.

If we can't easily avoid rendering all blocks (even if they're hidden) on first pass, we can probably skip re-rendering blocks if they're hidden during re-render.

**Additional context**

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #4229 

### Proposed Changes

Increases peformance of `toString` 50x. Used to take ~50ms, now takes <1ms.

### Reason for Changes

Speeeeed.

### Test Coverage

Just manual testing.

### Documentation

N/A

### Additional Information

N/A

### CODE REVIEW

File: core/block.ts [hunk 1]
```diff
@@ -1400,21 +1399,51 @@ export class Block implements IASTNodeLocation, IDeletable {
...
+    for (let i = 2; i < tokens.length; i++) {
+      if (tokens[i - 2] === '(' && tokens[i] === ')') {
+        tokens[i - 2] = tokens[i - 1];
+        tokens.splice(i - 1, 2);
+      }
+    }
 
-    let node = ASTNode.createBlockNode(this);
-    const rootNode = node;
+    let prev = '';
```
Comment (maribethb) [inline core/block.ts:1419]: Can you add the comment too? 

// Join the text array, removing the spaces around added parentheses.

**Review by maribethb — APPROVED** [review]
