### PR TITLE
fix: Properly size comments.

### LINKED ISSUE #8142: Workspace comments hide first line (Safari)
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Edit a workspace comment, and in Safari the first line disappears up under the top header.

### Reproduction steps

_No response_

### Stack trace

_No response_

### Screenshots

Screenshot 2024-05-17 at 15 20 06

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by NeilFraser**
Fixes multiple rendering and sizing issues across different browsers.

Tip: `text-overflow: hidden;` is not legal CSS and did nothing.

Resolves #8142

### CODE REVIEW

File: core/comments/rendered_workspace_comment.ts [hunk 1]
```diff
@@ -66,6 +66,15 @@ export class RenderedWorkspaceComment
       this,
       this.startGesture,
     );
+    // Don't zoom with mousewheel.
```
Comment (cpcallen) [inline core/comments/rendered_workspace_comment.ts:69]:
```suggestion
    // Don't zoom with mousewheel; let it scroll instead.
```

**Review by cpcallen — APPROVED** [review]
