### PR TITLE
fix: non-printable characters in XML

### LINKED ISSUE #4590: Blockly does not serialize non-printable characters correctly
**Describe the bug**

Blockly does not properly escape non-printable characters when serializing field inputs to XML.

XML does not accept all unicode characters. It only accepts the characters defined in [this range](https://www.w3.org/TR/xml/#charsets), and others need to be escaped. Currently Blockly is not properly escaping them.

**To Reproduce**

1. Add a block with a text input to the workspace.
2. Enter a non-printable character into the input. Eg on ubuntu you do `ctrl + shift + u` then `0001` to get a non-printable character.
3. Refresh to reload from XML.
4. Observe how the XML was unable to be parsed.

**Expected behavior**

Any text that it is possible for the user to enter into a field should serialize and deserialize properly.
[Edit: non-printable characters can also be input by the user via comments, so those values should be escaped as well]

**Additional context**

Related to: https://github.com/google/blockly/pull/1628 and https://github.com/mit-cml/appinventor-sources/pull/2370

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #4590 

### Proposed Changes

Makes it so that non-printable characters are properly escaped when serializing to XML, and that we do best-effort parsing when deserializing unescaped characters.

### Reason for Changes

App Inventor needs this to be pulled into core for them to be able to update.

### Test Coverage

Unit tests for serializing and deserializing.

### Documentation

N/A

### Additional Information

N/A

### CODE REVIEW

File: core/utils/xml.ts [hunk 1]
```diff
@@ -137,5 +146,11 @@ export function textToDomDocument(text: string): Document {
  */
 export function domToText(dom: Node): string {
   const oSerializer = new XMLSerializer();
-  return oSerializer.serializeToString(dom);
+  return sanitizeText(oSerializer.serializeToString(dom));
```
Comment (cpcallen) [inline core/utils/xml.ts:149]: Nit: please fix hungarian notation (`oSerializer` -> `serializer`) while you're at it.

File: tests/mocha/serializer_test.js [hunk 2]
```diff
@@ -1882,4 +1882,4 @@ const runSerializerTestSuite = (serializer, deserializer, testSuite) => {
 };
 
 runSerializerTestSuite(null, null, Serializer);
-runSerializerTestSuite((state) => state, (state) => state, Serializer);
+// runSerializerTestSuite((state) => state, (state) => state, Serializer);
```
Comment (cpcallen) [inline tests/mocha/serializer_test.js:1885]: Uncomment?

File: core/utils/xml.ts [hunk 3]
```diff
@@ -57,6 +57,9 @@ export function injectDependencies(dependencies: {
  */
 export const NAME_SPACE = 'https://developers.google.com/blockly/xml';
 
+// eslint-disable-next-line no-control-regex
+const INVALID_CONTROL_CHARS = /[\x00-\x09\x0B\x0C\x0E-\x1F]/g;
```
Comment (cpcallen) [inline core/utils/xml.ts:61]: What about surrogate pairs?  Does `XMLSerializer` handle those correctly already?

**Review by cpcallen — COMMENTED** [review]
I have so many questions about this, starting with: is `XMLSerialzer` really specced to return invalid XML which can't be parsed with `DOMParser`???

File: core/utils/xml.ts [hunk 4]
```diff
@@ -137,5 +146,11 @@ export function textToDomDocument(text: string): Document {
...
 export function domToText(dom: Node): string {
   const oSerializer = new XMLSerializer();
-  return oSerializer.serializeToString(dom);
+  return sanitizeText(oSerializer.serializeToString(dom));
+}
+
+function sanitizeText(text: string) {
+  return text.replace(
+      INVALID_CONTROL_CHARS,
+      (match) => `&#x${match.charCodeAt(0).toString(16)};`);
```
Comment (NeilFraser) [inline core/utils/xml.ts:155]: I'd recommend using decimal codes rather than hex.  Shorter (at least for smaller code points), faster, simpler.
`&#${match.charCodeAt(0)};`

File: core/utils/xml.ts [hunk 5]
```diff
@@ -108,10 +111,16 @@ export function createTextNode(text: string): Text {
...
 export function textToDom(text: string): Element {
-  const doc = textToDomDocument(text);
+  let doc = textToDomDocument(text);
   if (!doc || !doc.documentElement ||
       doc.getElementsByTagName('parsererror').length) {
-    throw Error('textToDom was unable to parse: ' + text);
+    const oParser = new DOMParser();
+    doc = oParser.parseFromString(text, 'text/html');
+    if (!doc || !doc.body.firstChild ||
+        doc.body.firstChild.nodeName.toLowerCase() != 'xml') {
```
Comment (NeilFraser) [inline core/utils/xml.ts:120]: Aren't we doing `!==` these days?

Comment (BeksOmega) [reply core/utils/xml.ts:120]: Whoops, was pulled over from the previous PR

File: core/utils/xml.ts (hunk 1 above)
Comment (BeksOmega) [reply core/utils/xml.ts]: I just removed the const assignment.

**Review by cpcallen — CHANGES_REQUESTED** [review]
Additional comments about `textToDom`, after discussion with Neil (but don't blame him if you don't like them!):

- AFAICT there's no reason to ever create more than one `DOMParser` (or `XMLSerializer`) instance, so I suggest having the module create a single module-local one and use it everywhere.
- `textToDomDocument` is only used by `textToDom` in this module (and nowhere else), so I suggest it be deprecated and have `textToDom` always use (the) `DOMParser` (instance) directly.
- I'm unclear about why `textToDom` tries parsing as HTML if parsing as XML fails.  That seems risky, and at least deserves an inline comment if not a note in the JSDoc.
- Normally I prefer handling errors at the top with an `if (fail) return;`, but in this case the error handlers end up getting nested, so I think it would be clearer to rewrite as:
  ```JS
  try xml
  if (xml win) return xml
  try html
  if (html win) return html
  throw 'I give up';
  ```

File: core/utils/xml.ts [hunk 6]
```diff
@@ -145,12 +145,10 @@ export function textToDomDocument(text: string): Document {
...
-  const oSerializer = new XMLSerializer();
-  return sanitizeText(oSerializer.serializeToString(dom));
+  return sanitizeText(new XMLSerializer().serializeToString(dom));
 }
 
 function sanitizeText(text: string) {
   return text.replace(
-      INVALID_CONTROL_CHARS,
-      (match) => `&#x${match.charCodeAt(0).toString(16)};`);
+      INVALID_CONTROL_CHARS, (match) => `&#x${match.charCodeAt(0)};`);
```
Comment (cpcallen) [inline core/utils/xml.ts:153]: Don't you need to lose the `x` too?

File: tests/mocha/serializer_test.js [hunk 7]
```diff
@@ -708,10 +708,10 @@ Serializer.Fields.Variable.Types = new SerializerTestCase('Types',
 Serializer.Fields.Variable.Tabs = new SerializerTestCase('Tabs',
     '<xml xmlns="https://developers.google.com/blockly/xml">' +
     '<variables>' +
-    '<variable id="aaaaaaaaaaaaaaaaaaaa">line1	line2	line3</variable>' +
+    '<variable id="aaaaaaaaaaaaaaaaaaaa">line1&amp;#x9line2&amp;#x9line3</variable>' +
```
Comment (NeilFraser) [inline tests/mocha/serializer_test.js:711]: Note that these tests still use hex.

File: core/utils/xml.ts [hunk 8]
```diff
@@ -133,8 +138,9 @@ export function textToDom(text: string): Element {
  * @throws if XML doesn't parse.
  */
 export function textToDomDocument(text: string): Document {
-  const oParser = new DOMParser();
-  return oParser.parseFromString(text, 'text/xml');
+  deprecation.warn(
+      'Blockly.utils.xml.textToDomDocument', 'version 10', 'version 11');
```
Comment (cpcallen) [inline core/utils/xml.ts:146]: Will our next release be v10?  If we release a 9.4 then this notice will actually be wrong.  🤔

Comment (BeksOmega) [reply core/utils/xml.ts:146]: yep this can't go in until @maribethb + @rachel-fenichel confirm whether we're doing a v9 or a v10

**Comment by BeksOmega** [comment]
@cpcallen Ok I think this is actually good for another look!

File: tests/mocha/xml_test.js [hunk 9]
```diff
@@ -73,13 +76,29 @@ suite('XML', function() {
...
+      assertXmlDoc(dom);
+      chai.assert.equal(
+          dom.getElementsByTagName('block').length, 6, 'Block tags');
+    });
+
+    test('text with NCR Control characters are properly deserialized',
+        function() {
+          const dom = Blockly.utils.xml.textToDom('<xml>&#x1;</xml>');
+          assertXmlDoc(dom);
+          chai.assert.equal(dom.firstChild.textContent, ''); // u0001
```
Comment (cpcallen) [inline tests/mocha/xml_test.js:92]: It looks like the character between the `''`s not a space but actually U+0001 / `0x01` / ascii `SOH` / `^a`—or rather it _completely fails to look like that_, the necessitating the comment.  Please use an escape sequence:

```suggestion
          chai.assert.equal(dom.firstChild.textContent, '\x01');
```
or
```suggestion
          chai.assert.equal(dom.firstChild.textContent, '\u0001');
```

(Despite the styleguide rule about comments for escape sequences I don't think one is required here because it's reasonably clear you are checking the decoding, rather than caring about the particular character in question.)

File: tests/mocha/xml_test.js [hunk 10]
```diff
@@ -73,13 +76,29 @@ suite('XML', function() {
...
-      chai.assert.equal(dom.nodeName, 'xml', 'XML tag');
-      chai.assert.equal(dom.getElementsByTagName('block').length, 6, 'Block tags');
+      assertXmlDoc(dom);
+      chai.assert.equal(
+          dom.getElementsByTagName('block').length, 6, 'Block tags');
+    });
+
+    test('text with NCR Control characters are properly deserialized',
+        function() {
+          const dom = Blockly.utils.xml.textToDom('<xml>&#x1;</xml>');
```
Comment (cpcallen) [inline tests/mocha/xml_test.js:90]: Please add a decimal NCR as well as the hex one, since the encoder uses decimal now (if I have understood correctly).

File: tests/mocha/xml_test.js (hunk 9 above)
Comment (cpcallen) [reply tests/mocha/xml_test.js:92]: (A type in the earlier version of the first suggestion has been fixed.)

File: core/utils/xml.ts (hunk 8 above)
Comment (BeksOmega) [reply core/utils/xml.ts:159]: For history: we are moving to v10

**Review by cpcallen — APPROVED** [review]
