### PR TITLE
fix: Use field ARIA labels for field-only blocks.

### LINKED ISSUE #9316: Screen reader output for full block fields
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

The screen reader output for full block fields is currently unhelpful. The field roles are on an element that isn't selected or even a descendent of what is focused and so aren't of any use for the screen reader output.

### Reproduction steps

1. Go to the [screen reader test page](https://google.github.io/blockly-keyboard-experimentation/screenreader/?scenario=navigationTestBlocks&toolbox=toolbox&renderer=zelos)
2. Navigate to any full block field
3. The screen reader will announce something generic rather than descriptive. See screenshot below.

### Stack trace

```shell

```

### Screenshots

Image

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #9316

### Proposed Changes
This PR makes blocks containing full-block fields derive their ARIA label from the label of their child field. Previously, these blocks did not have a label at all. The current field labels seem a bit suboptimal, but if they are updated that change will propagate through.

Because block labels are derived from their field labels, and Field's `getFocusableElement()` can throw if called early during initialization, I wrapped the access in a try-catch and moved the recalculation of the label into `initSvg()`, a bit later in the initialization sequence than the block constructor.

### CODE REVIEW

File: core/block_svg.ts [hunk 1]
```diff
@@ -239,15 +236,19 @@ export class BlockSvg
...
       // Shadow blocks are best represented directly by their field since they
       // effectively operate like a field does for keyboard navigation purposes.
       const field = Array.from(this.getFields())[0];
-      return (
-        aria.getState(field.getFocusableElement(), aria.State.LABEL) ??
-        'Unknown?'
-      );
+      try {
+        return (
+          aria.getState(field.getFocusableElement(), aria.State.LABEL) ??
```
Comment (maribethb) [inline core/block_svg.ts:246]: I think instead of trying to copy the label, this is what aria-labelledby is for? So we should put the id of the field's element here instead. Does that make any of what you were talking about earlier easier?

Comment (gonfunko) [reply core/block_svg.ts:246]: Seemingly so! Alas, https://issues.chromium.org/issues/40807024 exists, so I think we may be stuck with this.

Comment (maribethb) [reply core/block_svg.ts:246]: :/

**Review by maribethb — APPROVED** [review]
