### PR TITLE
Change lastConnectionInRow to getPlaceForOrphanedOutput

### LINKED ISSUE #3656: lastConnectionInRow inconsistent with lastConnectionInStack
**Describe the bug**

[lastConnectionInStack](https://github.com/google/blockly/blob/249d48477385f7ac389cb6f0dd9b2c06e9bc82dc/core/block.js#L533) lives on the block, while [lastConnectionInRow](https://github.com/google/blockly/blob/249d48477385f7ac389cb6f0dd9b2c06e9bc82dc/core/connection.js#L502) lives on the connection.

**Expected behavior**

Connection manipulation functions should be stored together. This makes them easier to use. And it makes it less likely that they will be accidentally duplicated.

**Additional context**

Both of these functions are package, so they can be safely moved.

In addition to the two above location options (connection or block) I would like to raise the option of moving these functions into their own "connection manipulation" file, as they don't access any private state. (lastConnectionInRow isn't even on the prototype)

[Todo link](https://github.com/google/blockly/blob/e2b510662cf60e4dba1e228f3b83549ea694e951/core/renderers/common/renderer.js#L192)

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Closes #3656

### Proposed Changes

Renames `lastConnectionInRow` and `singleConnection_` to better reflect what they're doing. But the main point of this was to add tests for `lastConnectionInRow`/`getPlaceForOrphanedOutput`.

No behavioral changes.

### Reason for Changes

Before I can tackle #4826 I need to write tests for everything, this is part of that.

### Test Coverage

Manually tested all of the behavior documented by #3658 to ensure nothing changed.

Tested on:
* Desktop Chrome

### CODE REVIEW

File: core/connection.js [hunk 1]
```diff
@@ -410,18 +411,19 @@ Blockly.Connection.singleConnection_ = function(block, orphanBlock) {
...
-  while ((connection = Blockly.Connection.singleConnection_(
-      /** @type {!Blockly.Block} */ (newBlock), orphanBlock))) {
-    newBlock = connection.targetBlock();
-    if (!newBlock || newBlock.isShadow()) {
-      return connection;
-    }
-  }
-  return null;
-};
+Blockly.Connection.getPlaceForOrphanedOutput =
```
Comment (moniika) [inline core/connection.js:414]: Why this rename? I prefer the name to include "Connection" in it rather than "Place", but I do like adding the "get" in front.
What about `getLastConnectionInRow`?

File: tests/mocha/connection_test.js [hunk 2]
```diff
@@ -784,4 +784,348 @@ suite('Connection', function() {
...
+          'message0': '',
+          'output': 'check',
+        },
+      ]);
+    });
+
+    teardown(function() {
+      workspaceTeardown.call(this, this.workspace);
+      delete Blockly.Blocks['input'];
+      delete Blockly.Blocks['output'];
```
Comment (moniika) [inline tests/mocha/connection_test.js:815]: These deletes are actually taken care of in the `sharedTestTeardown` call.
How it works is that the `defineBlocksWithJsonArray` is stubbed in `sharedTestSetup` to keep track of the block definitions that need deleted.

Same comment for the other definition deletes that were created through `defineBlocksWithJsonArray`.

File: core/connection.js (hunk 1 above)
Comment (BeksOmega) [reply core/connection.js:414]: I'm totally cool with swithcing `Place` to `Connection` but I don't think anything with `Last` or `Row` is an accurate representation of what this function is doing.

For example, pretend you did not know the logic this function is running. Would you expect something called `getLastConnectionInRow` to return the highlighted connection in these stacks of blocks:
middle
end

Or no connection for this stack of blocks:
none

Imo it's not a general use function. It's only used for finding a good connection to reattach an orphan to, so it should be named as such.

This is opposed to `lastConnectionInStack`, which ignores statement inputs and connection checks. This makes it consistant and general purpose, so I think the name is great in that situation.

File: tests/mocha/connection_test.js (hunk 2 above)
Comment (BeksOmega) [reply tests/mocha/connection_test.js]: Stubbing `defineBlocksWithJsonArray` to handle that is so smart! Deletions removed :D

**Review by moniika — APPROVED** [review]

**Comment by BeksOmega** [comment]
Sorry I accidently put this against master instead of develop :/ If there's anything I can do to fix it please let me know.

**Comment by moniika** [comment]
> Sorry I accidently put this against master instead of develop :/ If there's anything I can do to fix it please let me know.

My bad. I should have also double checked.
If you could make a new PR against develop. I will revert this change on master.
