### PR TITLE
Fix marker css

### LINKED ISSUE #3744: Unable to edit field when keyboard nav cursor is on block
**Describe the bug**

Unable to edit a field by clicking on it when the keyboard nav cursor is on a block. We're able to when its on a field, why not block?
@alschmiedt FYI

**To Reproduce**

1. Go to the playground, drag a number of blocks together
2. Enable keyboard nav
3. Traverse around such that the cursor is on a block like so: 
Screen Shot 2020-03-12 at 11 50 08 AM
4. Attempt to click on a field to edit it. Unable to click.

**Expected behavior**

Should be able to edit the field regardless what state we're in for keyboard nav.

**Screenshots**

Attached above.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
Fixes #3744

### Proposed Changes
Add pointer-events none

### Test Coverage

Tested on:

### CODE REVIEW

File: core/renderers/common/marker_svg.js [hunk 1]
```diff
@@ -569,7 +569,8 @@ Blockly.blockRendering.MarkerSvg.prototype.createDomInternal_ = function() {
       {
         'class': 'blocklyVerticalMarker',
         'rx': 10, 'ry': 10,
-        'style': 'display: none'
+        'style': 'display: none',
+        'pointer-events': 'none'
```
Comment (samelhusseini) [inline core/renderers/common/marker_svg.js]: Can this move to blocklyVerticalMarker.

Comment (alschmiedt) [reply core/renderers/common/marker_svg.js]: yup! updated.
