### PR TITLE
fix: gestures handling icons

### LINKED ISSUE #7099: Modify gesture system to handle icon clicks
### Description

In the past the icons would handle click on `pointerup` obviating the need for them to use the gesture system. For code unification purposes we want to change them to use the gesture system like everything else (in particular fields) does.

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #7099 

### Proposed Changes

Changes the gesture system to handle icon clicks.

### Reason for Changes

Code consistency.

### Test Coverage

Enabled last block -> icon hook tests.

### Documentation

N/A

### Additional Information

Dependent on #7100

### CODE REVIEW

**Review by rachel-fenichel — APPROVED** [review]

File: core/gesture.ts [hunk 1]
```diff
@@ -930,6 +939,17 @@ export class Gesture {
     this.bringBlockToFront();
   }
 
+  /** Execute an icon click. */
+  private doIconClick() {
+    if (!this.startIcon) {
+      throw new Error(
+        'Cannot do a field click because the start field is undefined'
```
Comment (BeksOmega) [inline core/gesture.ts:946]:
```suggestion
        'Cannot do a icon click because the start icon is undefined'
```
