### PR TITLE
Fixes theme error for headless workspaces

### LINKED ISSUE #2575: Headless Workspaces Require a Theme to Be Defined
### Problem statement

Headless workspaces require a theme to be defined, even though they are not rendered.

### Expected Behavior

I can create themed blocks on a headless workspace.

### Actual Behavior

I recieve an error.

### Steps to Reproduce

1. Disable the `changeTheme` function of the playground.
2. Remove all of the code from the `start` function and replace it with the below:
```
  var altWorkspace = new Blockly.Workspace();
  // JSON block def.
  var block = new Blockly.Block(altWorkspace, 'controls_if');
  // JS block def.
  var block = new Blockly.Block(altWorkspace, 'text_getSubstring');
```

### Stack Traces

```
block.js:1520 Block "controls_if": Style does not exist:  logic_blocks
  Blockly.Block.jsonInitStyle_ @ block.js:1520
  Blockly.Block.jsonInit @ block.js:1426
  (anonymous) @ blockly.js:414
  Blockly.Block @ block.js:181
  start @ playground.html:146
  onload @ playground.html:429

block.js:975 Uncaught Error: Trying to set block style to text_blocks before theme was defined via Blockly.setTheme().
    at Blockly.Block.setStyle (block.js:975)
    at Blockly.Block.init (text.js:224)
    at new Blockly.Block (block.js:181)
    at start (playground.html:147)
    at onload (playground.html:429)
```

### Additional Information

Just noticed this when I was writing some unit tests, and thought I should send it in.

Oh I also noticed that colour functions (some of them my own additions) are defined on the block rather than the rendered block, not sure if this is intensional.

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
#2575 & #2540

### Proposed Changes
Set a default theme in the workspace constructor.

### Reason for Changes
We were getting an error when creating a block on a headless workspace because the theme was not set. This is because we only set the default theme in Blockly.Inject which does not get called for a headless workspace.

### Test Coverage

Tested on:

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Makes sense.  One jsunit test is failing.

File: tests/jsunit/block_test.js [hunk 1]
```diff
@@ -279,6 +280,7 @@ function test_set_style() {
   assertEquals('#ddeeff', blockA.colourTertiary_);
 
   blockTest_tearDown();
+  \
```
Comment (rachel-fenichel) [inline tests/jsunit/block_test.js]: ?

Comment (alschmiedt) [reply tests/jsunit/block_test.js]: removed.
