### PR TITLE
fix: work on calling icon hooks

### LINKED ISSUE #7098: Call new icon hooks in block rendering code
### Description

Actually call new hooks like `initView`, `applyColour`, `updateEditable`, and `updateCollapsed` at the appropriate places.

### LINKED ISSUE #7099: Modify gesture system to handle icon clicks
### Description

In the past the icons would handle click on `pointerup` obviating the need for them to use the gesture system. For code unification purposes we want to change them to use the gesture system like everything else (in particular fields) does.

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I branched from develop
- [X] My pull request is against develop
- [X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [X] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #7098

### Proposed Changes

Adds correctly calling the new icon hooks in a bunch of places.

### Reason for Changes

Actually get the code to work for testing refactoring icons.

### Test Coverage

Enabling tests yay!

### Documentation

N/A

### Additional Information

Two of the `initView` tests are still skipped because I need to fix #7099 first.

### CODE REVIEW

File: core/render_management.ts [hunk 1]
```diff
@@ -138,12 +140,23 @@ function updateConnectionLocations(block: BlockSvg, blockOrigin: Coordinate) {
...
+    if (isIcon(icon)) {
+      icon.onLocationChange(blockOrigin);
+    } else {
+      // TODO (#7042): Remove old icon handling code.
+      icon.computeIconLocation();
+    }
   }
-  for (const child of block.getChildren(false)) {
-    updateIconLocations(child);
+  for (const conn of block.getConnections_(false)) {
```
Comment (maribethb) [inline core/render_management.ts:153]: I don't understand this change -- doesn't `getChildren` already return the blocks connected via input and next connections? Using `getChildren` is more readable and already does some of the work like not finding previous connections and skipping connections with no blocks attached. I'm sure I'm missing something though.

File: core/renderers/common/drawer.ts [hunk 2]
```diff
@@ -321,7 +328,13 @@ export class Drawer {
     if (this.info_.isInsertionMarker) {
       // Fields and icons are invisible on insertion marker.  They still have to
       // be rendered so that the block can be sized correctly.
-      svgGroup.setAttribute('display', 'none');
+      if (isIcon((fieldInfo as Icon).icon)) {
```
Comment (maribethb) [inline core/renderers/common/drawer.ts:331]: 😵‍💫

**Review by maribethb — APPROVED** [review]

File: core/renderers/common/drawer.ts (hunk 2 above)
Comment (BeksOmega) [reply core/renderers/common/drawer.ts:331]: Haha I'll do another look at cleaning this up, but I think this method just needs to be split into some submethods

File: core/render_management.ts (hunk 1 above)
Comment (BeksOmega) [reply core/render_management.ts:153]: We could iterate the children, but we'd need to access their connections anyway to get the `relativeCoords` so we can do the fancy efficient math. So I think this is more readable given that constraint? but I can also check doing it the other way

Comment (maribethb) [reply core/render_management.ts:153]: Isn't `target` === `child` (in the way the code was before)? 

So iiuc the code would be

```
for (const child of block.getChildren(false)) {
  updateIconLocations(target, Coordinate.sum(blockOrigin, child.relativeCoords))
}
```

File: core/renderers/common/drawer.ts (hunk 2 above)
Comment (maribethb) [reply core/renderers/common/drawer.ts:331]: I'm assuming that when you remove handling the old types some of these if statements will go away (though maybe not here since you didn't leave the comment about removing it?) so I tried not to comment on that aspect of them, but this one got me lol. I don't think you really need to change anything here unless you think it's actually possible to improve htis. but don't bother if it will be removed in 7042

File: core/render_management.ts (hunk 1 above)
Comment (BeksOmega) [reply core/render_management.ts:153]: Oh whoops you're right I was reading this wrong. I thought `target` was `targetConnection` not `targetBlock`. Can fix =)
