### PR TITLE
Propagate the visible state when blocks connect

### LINKED ISSUE #1967: Hidden statement inputs seem broken
### Problem
If I attach a block to a hidden statement input (reasonably expecting that block to be hidden), the block is programmatically attached to the input, but shown free-floating on the workspace.

### Expected behavior
The "visible" flag of the input should cascade down to anything attached to it.

### Actual Behavior

Actual behavior is basically "Weird".

I can verify programmatically that the block is attached to the input, but visually it just appears near the block with the input on the work-space and I drag it around free-form.

This makes hiding a statement input somewhat futile.

### Steps to reproduce
I have code like this:

```
        const summaryInput = this.appendStatementInput("summaryCollection");
        summaryInput.setVisible(false);
        summaryInput.connection.connect(blockToAttach.previousConnection);
```

blockToAttach ends up showing detached on the workspace (even though it is in fact attached in the block model).

### Workaround

As I can't see a way of hiding a block (looking at the Block API), I'm not sure what the workaround is.

### PR DESCRIPTION
**Pull request by RoboErikG**
This fixes #1967.

In rendered connections when connecting:
- If the superior connection is hidden this hides the newly connected block.
- If the superior connection isn't hidden it makes sure the block is visible.

In rendered connections when disconnecting:
- If the superior connection is hidden, make the disconnected block stack visible.

TODO before review: write tests.

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#1967

### Proposed Changes

Adds logic to rendered_connection to hide or unhide blocks when they are connected to a hidden connection.

### Reason for Changes

If you programatically connect a block to a hidden connection the block remains visible and gets placed in a random spot. The block should be hidden when connected and unhidden when disconnected.

### Test Coverage

Tested on:
Desktop Chrome

### Additional Information

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly/2003)

### CODE REVIEW

**Comment by RoboErikG** [comment]
This still needs more work. It seems to be working, but there were quite a few edge cases that I had to fix and I don't think I've caught them all.

**Comment by RoboErikG** [comment]
This turns out to be more complicated than expected. There are quite a few cases that go through different paths and have differing state depending on the timing. #2003 is a start at a fix but needs a lot of tests to be sure all cases are covered correctly.

Notes from working on this:
- Calling connect directly didn't create an undo group. Anyone else using connect as an API would have had to create an event group before calling it or they'd get into a weird state.
- Connection.connect and Connection.disconnect both needed to be overridden by rendered_connection, and there's probably some additional work to do in respawnShadow_.
- The code paths for users dragging blocks around, calling APIs directly, and undoing/redoing events are all slightly different and need testing.

**Comment by AnmAtAnm** [comment]
Four lint errors in `rendered_connection.js`:
```
337:36  error  Trailing spaces not allowed  no-trailing-spaces
343:64  error  Missing semicolon            semi
347:2   error  Missing semicolon            semi
365:2   error  Missing semicolon            semi
```

File: tests/workspace_svg/rendered_connection_test.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ * limitations under the License.
+ */
+'use strict';
+
+goog.require('goog.testing');
+goog.require('goog.testing.MockControl');
+
+
+function renderedConnectionTest_setup() {
+
```
Comment (AnmAtAnm) [inline tests/workspace_svg/rendered_connection_test.js]: Intending to complete these before merging?

Comment (RoboErikG) [reply tests/workspace_svg/rendered_connection_test.js]: Yes, I need to write tests still. Probably won't happen for a week or two.

**Comment by RoboErikG** [comment]
Tests added! This PR is now ready to go once there's a final review.

File: tests/mocha/connection_test.js [hunk 2]
```diff
@@ -0,0 +1,321 @@
...
+        "nextStatement": null
+      },]);
+
+      var toolbox = document.getElementById('toolbox-connections');
+      this.workspace = Blockly.inject('blocklyDiv', {toolbox: toolbox});
+    });
+
+    teardown(function() {
+      delete Blockly.Blocks['stack_block'];
+      delete Blockly.Blocks['row_block'];
```
Comment (rachel-fenichel) [inline tests/mocha/connection_test.js]: Also delete `inputs_block`

Comment (RoboErikG) [reply tests/mocha/connection_test.js]: Done.
