### PR TITLE
Work around a problem with RTL mutators

### LINKED ISSUE #1425: Delete areas broken in RTL Mutators on FF
Demo:
https://www.youtube.com/watch?v=DIdfREakzpg

Try here:
https://blockly-demo.appspot.com/static/demos/rtl/index.html

### PR DESCRIPTION
**Pull request by rachel-fenichel**
## The basics
- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #1425 
### Proposed Changes

Change the calculation of the delete area for flyouts in mutators in RTL in firefox.  Explicitly add an offset from the left side of the mutator.

### Reason for Changes

See #1425, but TLDR: Firefox is reporting the wrong value, and that bug has been around for years.  We surfaced it with a combination of changes to our DOM structure and changes to delete logic.

### Test Coverage

Tested in the playground in Firefox in RTL mode, with the if/else mutator.
Tested at a variety of scales.
Also tested in LTR mode to make sure there are no regressions.

Tested in Chrome to confirm no regressions.

Tested on:
* Desktop Chrome
* Desktop Firefox

### Additional Information

As soon as we merge this they're going to fix Firefox and this will all break again :(

This should unblock the Blockly Games release.

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Updated to use the browser's value if it looks reasonable.  This should protect us if Firefox eventually fixes the bug.

File: core/flyout_vertical.js [hunk 1]
```diff
@@ -155,8 +155,13 @@ Blockly.VerticalFlyout.prototype.position = function() {
   var x = targetWorkspaceMetrics.absoluteLeft;
   if (this.toolboxPosition_ == Blockly.TOOLBOX_AT_RIGHT) {
     x += (targetWorkspaceMetrics.viewWidth - this.width_);
+    // Save the location of the left edge of the flyout, for use when firefox
+    // gets the bounding client rect wrong.
+    this.leftEdge_ = x;
   }
   this.positionAt_(this.width_, this.height_, x, y);
+
+
```
Comment (AnmAtAnm) [inline core/flyout_vertical.js]: NIT: Excess newlines.

File: core/flyout_vertical.js [hunk 2]
```diff
@@ -155,8 +155,13 @@ Blockly.VerticalFlyout.prototype.position = function() {
   var x = targetWorkspaceMetrics.absoluteLeft;
   if (this.toolboxPosition_ == Blockly.TOOLBOX_AT_RIGHT) {
     x += (targetWorkspaceMetrics.viewWidth - this.width_);
+    // Save the location of the left edge of the flyout, for use when firefox
```
Comment (NeilFraser) [inline core/flyout_vertical.js]: Firefox is usually capitalized.

File: core/flyout_vertical.js (hunk 1 above)
Comment (NeilFraser) [inline core/flyout_vertical.js]: Adding blank lines?

Comment (rachel-fenichel) [reply core/flyout_vertical.js]: Done.

**Comment by rachel-fenichel** [comment]
Yeah, I'm not at all happy with it but it's been blocking for too long, and we *do* know exactly what conditions trigger it.

We may eventually fix the root cause the next time we work on the general DOM structure, but that's not going to be soon.

**Comment by rachel-fenichel** [comment]
Updated the math to check whether the browser's value is right, and added a comment to explain what's going on. Thanks for the check @picklesrus!

Tested in Chrome by disabling the user-agent check.  In Chrome on RTL (when the browser isn't lying) it does the right thing as well.

File: core/flyout_vertical.js [hunk 3]
```diff
@@ -323,15 +323,23 @@ Blockly.VerticalFlyout.prototype.getClientRect = function() {
...
+      var targetWsLeftPixels =
+          this.targetWorkspace_.svgGroup_.getBoundingClientRect().x;
+      // The client rect is in pixels relative to the window origin.  When the
+      // browser gets the wrong value it reports that the flyout left is the
+      // same as the mutator workspace left.
+      // We know that in a mutator workspace with the flyout on the right, the
+      // visible area of the workspace should be more than ten pixels wide.  If
+      // the browser reports that the flyout is within ten pixels of the left
+      // side of the workspace, ignore it and manually calculate the value.
+      if (Math.abs(targetWsLeftPixels - x) < 10) {
```
Comment (AnmAtAnm) [inline core/flyout_vertical.js]: Will the 10px assumption be invalidated if we allow mutators without flyouts/with empty flyouts, à la #1759. In practice, a mutator with an empty/invisible empty toolbox (no way to add new blocks), probably doesn't a need for a block delete area.  Technically, the issues are distinct.

Comment (rachel-fenichel) [reply core/flyout_vertical.js]: At that point there should be no flyout, so nothing to call `getClientRect` on.  Then this code won't be hit.
