### PR TITLE
Fix #1487 and only add the delete cursor if the block is not deletabl…

### LINKED ISSUE #1487: Undeletable blocks have delete icon when dragged over category toolbox
Go to playground and import this XML:
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block deletable="false" type="controls_if"></block>
</xml>
```
Drag the block over the toolbox.  Icon shows delete cross.  Expect to see the normal dragging hand instead.

This is a regression within the past year (Blockly Games does not do this).

### PR DESCRIPTION
**Pull request by picklesrus**
…e. Also add a grab cursor when it is not deletable so the cursor keeps the grab hand when over the toolbox.  This changes the toolbox api slightly, but the methods it touches are @package so it should be okay.

## The basics

- [x ] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#1487 

Tested on:
 * Desktop Chrome 
 * Desktop Firefox

### CODE REVIEW

File: core/block_dragger.js [hunk 1]
```diff
@@ -168,7 +168,9 @@ Blockly.BlockDragger.prototype.startBlockDrag = function(currentDragDeltaXY) {
   this.draggingBlock_.moveToDragSurface_();
 
   if (this.workspace_.toolbox_) {
-    this.workspace_.toolbox_.addDeleteStyle();
+    var style = this.draggingBlock_.isDeletable() ? 'blocklyToolboxDelete' :
+      'blocklyToolboxGrab';
```
Comment (NeilFraser) [inline core/block_dragger.js]: More indent here.  And once below at 230.
