### PR TITLE
fix: flyout id is different than first placed block

### LINKED ISSUE #7432: First block from flyout matches ID and subsequent ones do not
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you drag a block from the flyout for the first time, the block has the same ID as the block in the flyout. For subsequent blocks it has a different ID.

The first block has the same ID because we are serializing the flyout block and deserializing it into the main workspace (ids are included in serialization). Subsequent blocks do not have the same ID, because during deserialization the ID conflicts with the block that already exists in the workspace, so it gets a new ID.

This causes problems with unit tests because we have multiple blocks on the page that have the same `[data-id]` attribute.

Instead it would be nice if all blocks dragged from the flyout have a different ID than their originator.

We should add a `saveIds` parameter to `Blockly.serialization.blocks.save` that allows us to save blocks without IDs. If we save the blocks in the flyout like this and then deserialize them, we ensure that the IDs are always different.

### Reproduction steps

1. Run `npm run start` from the root of the repository.
2. Switch from "Category toolbox" to "Simple toolbox"
3. Drag the if-else block from the flyout.
4. Inspect the page for both the block in the flyout and the block on the main workspace. Observe how the `data-id` attribute is the same for both.

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Add a new optional `addIds` parameter to the [save function](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/serialization/blocks.ts#L82) that defaults to `true`.
3) Change the logic to only save the Id if `addIds` is true.
4) Pass the parameter through all the recursive calls. Namely `saveInputBlocks` and `saveNextBlocks`.
5) Modify the [flyout code](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/flyout_base.ts#L1216) to pass `addIds: false` to `save`.
6) Run the reproduction steps again and make sure the blocks have different IDs.

### PR DESCRIPTION
**Pull request by treypisano**
## The basics

- [ x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes  #7432 

### Proposed Changes

Adds a parameter,  `saveIds: boolean`, to the [`save`](https://github.com/google/blockly/blob/4ab8d000995a93eafbc29444abb76e535aedf134/core/serialization/blocks.ts#L82) function. I also made sure that the parameter is passed through the recursive calls.

### Reason for Changes

This ensures that when a block is dragged out, the ID of the newly placed block is different than the one in the flyout. 

### Test Coverage

1. Open up the flyout, inspect the if block and note the data-id attribute 
2. Drag the block out, note the data-id attribute
3. The data-ids are not the same

### CODE REVIEW

File: core/serialization/blocks.ts [hunk 1]
```diff
@@ -270,6 +281,7 @@ function saveInputBlocks(
   block: Block,
   state: State,
   doFullSerialization: boolean,
+  addIds: boolean,
```
Comment (BeksOmega) [inline core/serialization/blocks.ts:284]: Can you make this `saveIds` so that it's consistent?

**Review by BeksOmega — CHANGES_REQUESTED** [review]
First look seems good =) I'll pull it down and give it a manual test in a bit!

Would you also be interested in writing a tiny unit test in our [block serialization suite](https://github.com/google/blockly/blob/4003093404785825d6dd009190cf312ce5f44654/tests/mocha/jso_serialization_test.js#L49) that tests that when `saveIds` is false, there aren't IDs?

Thank you for your work on this @treypisano :D

**Comment by treypisano** [comment]
Sure, I'll write that test.

File: core/serialization/blocks.ts [hunk 2]
```diff
@@ -86,20 +86,21 @@ export function save(
...
   } = {},
 ): State | null {
   if (block.isInsertionMarker()) {
     return null;
   }
-
   const state = {
     'type': block.type,
-    'id': block.id,
+    'id': saveIds ? block.id : null,
```
Comment (BeksOmega) [inline core/serialization/blocks.ts:103]: We actually want this to be `undefined` instead of `null`. `null` gets stringified and takes up space in the save data, but `undefined` does not get serialized.

E.g. if you pass an object like the following to `JSON.stringify`:
```
{
  propertyA: null,
  propertyB: undefined
}
```
You get:
```
'{"propertyA": null}'
```

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Just one fix and then LGTM!

File: core/serialization/blocks.ts (hunk 2 above)
Comment (treypisano) [reply core/serialization/blocks.ts:103]: Got it, I hadn't thought of it that way

**Review by BeksOmega — APPROVED** [review]
LGTM! Thank you for your work on this @treypisano =)
