### PR TITLE
fix: TS errors on dependent projects with certain tsconfig settings (#6360)

### LINKED ISSUE #6360: TypteScript compilation errors in dependent project with certain tsconfig settings
I have a TS project that depends on blockly. When upgrading my blockly version to `9.0.0-beta.0`, I have the following errors when doing `tsc --watch` in my project:

    [11:27:56 AM] Starting compilation in watch mode...

    node_modules/blockly/core/block.ts:1416:22 - error TS2339: Property 'substring' does not exist on type 'any[]'.

    1416         text = (text.substring(0, opt_maxLength - 3) + '...') as
                              ~~~~~~~~~

    node_modules/blockly/core/block.ts:1420:5 - error TS2322: Type 'any[]' is not assignable to type 'string'.

    1420     return text;
             ~~~~~~~~~~~~

    node_modules/blockly/core/field_registry.ts:71:7 - error TS2352: Conversion of type 'Field' to type 'IRegistrableField' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
      Property 'fromJson' is missing in type 'Field' but required in type 'IRegistrableField'.

    71       registry.getObject(registry.Type.FIELD, options['type']) as
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    72           IRegistrableField |
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    73       null;
       ~~~~~~~~~~

      node_modules/blockly/core/interfaces/i_registrable_field.ts:30:3
        30   fromJson: fromJson;
             ~~~~~~~~
        'fromJson' is declared here.

    node_modules/blockly/core/generator.ts:162:17 - error TS2339: Property 'replace' does not exist on type 'any[]'.

    162     code = code.replace(/\n\s+$/, '\n');
                        ~~~~~~~

    node_modules/blockly/core/generator.ts:163:17 - error TS2339: Property 'replace' does not exist on type 'any[]'.

    163     code = code.replace(/[ \t]+\n/g, '\n');
                        ~~~~~~~

    node_modules/blockly/core/generator.ts:164:5 - error TS2322: Type 'any[]' is not assignable to type 'string'.

    164     return code;
            ~~~~~~~~~~~~

    node_modules/blockly/core/utils/toolbox.ts:428:3 - error TS2322: Type 'string | Element' is not assignable to type 'Element'.
      Type 'string' is not assignable to type 'Element'.

    428   return toolboxDef;

**To Reproduce**

Have a project that depends on blockly@9.0.0-beta.0 with the following tsconfig.json file. Note that the above errors cannot be bypassed even when setting `skipLibCheck` to `true`.

    {
        "compileOnSave": true,
        "compilerOptions": {
            "target": "es6",
            "module": "commonjs",
            "sourceMap": false,
            "removeComments": true,
            "listEmittedFiles": false,
            "newLine": "LF",
            "downlevelIteration" : true,
            "incremental": true,
            "jsx": "react",
            "resolveJsonModule": true,
            "lib": [
                "dom",
                "es2021",
                "WebWorker",
            ],
            "skipLibCheck": true,
            "baseUrl": ".",
            "paths": {
                "shared/*": ["src/shared/*"]
            },
        },
    }

An easier way to reproduce the same errors is to mess with the tsconfig.json file of the blockly project directly: (Changes are marked with ****). Then run `tsc --watch`.

    {
      "include": [
        "core/**/*",  // N.B.: also pulls in closure/goog/goog.js if needed.
        "closure/**/*",  // Just for ouptut directory structure.
      ],
      "exclude": [
        "core/blockly.js"
      ],
      "compilerOptions": {
        "allowJs": false, // **** set this to false
        "declaration": true,
        "sourceMap": true,
    
        "module": "ES2015",
        "moduleResolution": "node",
        "target": "ES2020",
        "strict": false, // **** set this to false
        
        // **** add the 'lib' and 'skipLibCheck' entries
        "lib": [
            "dom",
            "es2021",
            "WebWorker",
        ],
        "skipLibCheck": true,
      }
    }

**Desktop:**
 - OS: Ubuntu 22.04
-  tsc: 4.4.3

### PR DESCRIPTION
**Pull request by ktbytechibong**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

resolves #6360

### Proposed Changes

Fairly minor refactoring to bypass some typescript errors appearing on dependent projects with certain tsconfig settings.

#### Behavior Before Change

N/A. No behavioral changes. 

#### Behavior After Change

N/A. No behavioral changes. 

### Test Coverage

Existing tests should cover my changes:
- run_node_test.js covers `Generator#workspaceToCode`
- toolbox_test.js has "parseToolbox" suite covers `parseToolboxTree`
- block_test.js has "toString" suite to test `Block#tostring`

Ran `npm run test` and all existing tests passed.

### CODE REVIEW

File: core/field_registry.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ export function fromJson(options: AnyDuringMigration): Field|null {
  */
 function fromJsonInternal(options: AnyDuringMigration): Field|null {
   const fieldObject =
-      registry.getObject(registry.Type.FIELD, options['type']) as
+      registry.getObject(registry.Type.FIELD, options['type']) as unknown as
```
Comment (cpcallen) [inline core/field_registry.ts:71]: This smells bad.  From your bug report it looks like `tsc` is correctly deducing that `getObject` is returning a `Field`, and the error message (that `Field` is not assignable to `IRegisterableField` appears to be legit.

I think part of the problem may be that `IRegisterableField` is now incorrectly defined: [it was originally specifically _not_ an `@interface`](https://github.com/google/blockly/blob/d86cec9145edd36d7d0f89806371bc184116c948/core/interfaces/i_registrable_field.js#L27) because it's really supposed to be declaring a type that has a certain `static` method (i.e., property on the constructor function object) named `fromJson`, rather than declaring that it is a type with an _instance_ method (i.e., property on the `.prototype` object) named `from Json`, but this appears to have been erroneously converted to an `interface` by PR #6299.

So I think the fix here is one or more of the following:

1. Correct [the definition of `IRegisterableField`](https://github.com/google/blockly/blob/883d78d5a09a6f45b4982943e57c5e9dbd3fbc7e/core/interfaces/i_registrable_field.ts#L29), possibly by using [this decorator pattern](https://stackoverflow.com/a/43674389/4969945).
2. Correct [the definition of of `Type.FIELD`](https://github.com/google/blockly/blob/883d78d5a09a6f45b4982943e57c5e9dbd3fbc7e/core/registry.ts#L81) to use `IRegisterableField` instead of `Field`.
3. Add a runtime typecheck to make sure the `Field` returned by `registry.getObject` is actually an `IRegisterableField`—tricky, since interfaces are not concrete types that can be checked with `instanceof`, but possibly something like this might work:
   ```
   if (typeof Object.getPrototypeOf(fieldObject).constructor.fromJson !== 'function) {
     throw new TypeError('returned Field was not a IRegisterableField');
    }
   ```
   (I'm not sure `tsc` is clever enough to do the necessary inference, and in any case this only checks for the existence of a `fromJson` static method, not that method's signature.)

Maybe @maribethb can weigh in on what the correct type of the template parameter to `registry.Type.FIELD` should be; I'm weirded out by the lack of overlap between `Field` and `IRegisterableField` which seems like it ought to be a subclass of the former.

File: core/block.ts [hunk 2]
```diff
@@ -1309,7 +1309,7 @@ export class Block implements IASTNodeLocation, IDeletable {
    * @return Text of block.
    */
   toString(opt_maxLength?: number, opt_emptyToken?: string): string {
-    let text = [];
+    const text = [];
```
Comment (cpcallen) [inline core/block.ts:1312]: I think I'd have a mall preference to rename this variable, and keep `text` as the name of the combined `string` variable.  But (unlike the similar case in `generator.ts` below) `lines` isn't an accurate name, so maybe you can suggest something?  But if no better idea surfaces then then the choice you've made here is fine.

**Review by cpcallen — CHANGES_REQUESTED** [review]
Hello and thank you for sending us this useful pull request; it is appreciated!

It mostly looks great, but there is one place where I am hoping you might be able to suggest a better choice of name, and another where I think there is an actual error in our type definitions (maybe several errors) that should be fixed.

**Comment by cpcallen** [comment]
Assigning to @maribethb for follow-up review as I will be on annual leave until 20th August.

File: core/field_registry.ts (hunk 1 above)
Comment (ktbytechibong) [reply core/field_registry.ts:71]: Agreed that this is not ideal. I don't know enough about the code base to make a decision though. Will wait for suggestion.

**Comment by ktbytechibong** [comment]
@btw17 commented that #6360 should be fixed with #6362. This PR will still clean up some code, but not nearly as useful after that fix is merged.

File: core/block.ts (hunk 2 above)
Comment (cpcallen) [reply core/block.ts:1312]: Yes, `tokens` sounds good.

File: core/field_registry.ts (hunk 1 above)
Comment (cpcallen) [reply core/field_registry.ts:71]: @maribethb, do you have an opinion on this?

Comment (BeksOmega) [reply core/field_registry.ts:71]: I think the best/simplest option for now is Option 3. Do a runtime check that the fieldObject (which is actually a field constructor) has a fromJson method on it, and throw a useful error if it does not. That way we know we at least have runtime safety.

We can discuss better solutions to defining the static method on a type later.

**Comment by ktbytechibong** [comment]
Ok, addressed comments in the PR. Thanks.

**Review by BeksOmega — APPROVED** [review]
Thanks for the fixes! LGTM =) If/once CI passes I'll go ahead and merge this, and it will go into our next release!
