### PR TITLE
fix: Utilize getIcon instead of getCommentIcon in tests

### LINKED ISSUE #7164: Remove calls to `getCommentIcon` in tests
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The mocha tests are currently outputting deprecation warnings to the console because of calls to `getCommentIcon`.

### Request

Replace calls to `getCommentIcon` with calls to `getIcon(CommentIcon.TYPE)`

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jibranabsarulislam**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

### Resolves

Fixes #7164 

### Proposed Changes

utilize `getIcon()` in preparation for v11

### Behavior Before Change
image

### Behavior After Change
image

### Reason for Changes

> The mocha tests are currently outputting deprecation warnings to the console because of calls to getCommentIcon. (https://github.com/google/blockly/issues/7164#issue-1757210807)

### Test Coverage

`npm run test:mocha:interactive` -> check console

### Documentation

Removed deprecation function, docstring, and dependencies from `block_svg.ts`

### Additional Information

N/A

### CODE REVIEW

File: core/block_svg.ts [hunk 1]
```diff
@@ -888,18 +886,6 @@ export class BlockSvg
...
   }
 
-  /**
-   * Get the comment icon attached to this block, or null if the block has no
-   * comment.
-   *
-   * @returns The comment icon attached to this block, or null.
-   * @deprecated Use getIcon. To be remove in v11.
-   */
-  getCommentIcon(): CommentIcon | null {
```
Comment (BeksOmega) [inline core/block_svg.ts:898]: Could you revert the changes to this file? We're not ready to delete this yet. We're deprecating this in v10 (coming out at the end of this month) and then deleting it in v11!

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Thanks for the fix, this looks great :D Just one fixup and then this should be good to go!

File: core/block_svg.ts (hunk 1 above)
Comment (jibranabsarulislam) [reply core/block_svg.ts:898]: on it, thank you!

**Review by BeksOmega — APPROVED** [review]

File: tests/mocha/comment_deserialization_test.js [hunk 2]
```diff
@@ -10,6 +10,7 @@ import {
   sharedTestSetup,
   sharedTestTeardown,
 } from './test_helpers/setup_teardown.js';
+import {CommentIcon} from '../../core/icons/comment_icon.js';
```
Comment (cpcallen) [inline tests/mocha/comment_deserialization_test.js:13]: I believe this should have been `from '../../build/src/core/icons/comment_icon.js'` (here and below).

We are now seeing build warnings that I believe are due to this; I'm actually not certain how this test is running successfully as I would not expect the import as written to work at all:

```
Could not find "../../core/icons/comment_icon.js".Assuming it (and its transitive dependencies) are non-Closure managed. /Users/cpcallen/src/blockly/tests/mocha/comment_deserialization_test.js
Could not find "../../core/icons/comment_icon.js".Assuming it (and its transitive dependencies) are non-Closure managed. /Users/cpcallen/src/blockly/tests/mocha/contextmenu_items_test.js
...
```
