### PR TITLE
chore!: Fix warnings when generating docs.

### LINKED ISSUE #6936: Errors from api-extractor and api-documenter (in v9.3.0 release)
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Preparing to update the devsite documentation following the 9.3.0 release, I observed the following errors from api-extractor:
```
api-extractor 7.34.4  - https://api-extractor.com/

Using configuration from ./api-extractor.json
Analysis will use the bundled TypeScript version 4.8.4
*** The target project appears to use TypeScript 5.0.2 which is newer than the bundled compiler engine; consider upgrading API Extractor.
Warning: dist/core/events/events_var_delete.d.ts:12:4 - (tsdoc-undefined-tag) The TSDoc tag "@class" is not defined in this configuration
Warning: dist/core/events/events_var_rename.d.ts:12:4 - (tsdoc-undefined-tag) The TSDoc tag "@class" is not defined in this configuration
Warning: dist/core/interfaces/i_observable.d.ts:11:1 - (ae-internal-missing-underscore) The name "IObservable" should be prefixed with an underscore because the declaration is marked as @internal
Warning: dist/core/interfaces/i_observable.d.ts:20:1 - (ae-internal-missing-underscore) The name "isObservable" should be prefixed with an underscore because the declaration is marked as @internal
Warning: dist/core/rendered_connection.d.ts:67:8 - (tsdoc-undefined-tag) The TSDoc tag "@return" is not defined in this configuration
Warning: dist/core/rendered_connection.d.ts:76:8 - (tsdoc-undefined-tag) The TSDoc tag "@return" is not defined in this configuration
Warning: dist/core/rendered_connection.d.ts:86:8 - (tsdoc-undefined-tag) The TSDoc tag "@return" is not defined in this configuration
```
and from api-documenter:
```
api-documenter 7.19.26  - https://api-extractor.com/

Reading blockly.api.json

Deleting old output from docs
Writing blockly package
WARNING: Unable to resolve reference "Block#toString": The package "Block" could not be located
WARNING: Unable to resolve reference "Block#toString": The package "Block" could not be located
Unsupported block tag: @class
Unsupported block tag: @class
Unsupported block tag: @class
Unsupported block tag: @class
WARNING: Unable to resolve reference "IMetricsManager#getFlyoutMetrics": The package "IMetricsManager" could not be located
WARNING: Unable to resolve reference "IMetricsManager#getFlyoutMetrics": The package "IMetricsManager" could not be located
WARNING: Unable to resolve reference "MetricsManager#getFlyoutMetrics": The package "MetricsManager" could not be located
WARNING: Unable to resolve reference "MetricsManager#getFlyoutMetrics": The package "MetricsManager" could not be located
Unsupported block tag: @return
Unsupported block tag: @return
Unsupported block tag: @return
```

### Reproduction steps

1. `git checkout master`
2. `npm ci && npm run package && npm run docs`
3. Observe error messages.

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

### Resolves

Fixes #6936

### Proposed Changes
This PR resolves various warnings when generating documentation. It fixes the @link syntax in various docstrings to either be valid or disambiguate the symbol being referenced, removes @class on docstrings attached to a class, unifies docs for setters/getters to be on the getter, and updates the API Extractor config to not require leading underscores on internal symbols.

### Breaking Change
`WorkspaceSvg.getLayerManager()` is now marked `@internal`; API Extractor was complaining that the class itself was internal but had a public getter. The PR that introduced the layer manager and this method (#7619) stated that "The new system should be entirely internal.", so I believe this being public was an oversight.

The `IRenderedElement` interface is made public by this change.

### CODE REVIEW

File: core/interfaces/i_rendered_element.ts [hunk 1]
```diff
@@ -4,18 +4,15 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
-/** @internal */
 export interface IRenderedElement {
   /**
-   * @returns The root SVG element of htis rendered element.
+   * @returns The root SVG element of this rendered element.
```
Comment (rachel-fenichel) [inline core/interfaces/i_rendered_element.ts:9]: Add a note to the top-level PR description that this PR also makes `IRenderedElement` public.

**Review by rachel-fenichel — APPROVED** [review]

File: core/interfaces/i_rendered_element.ts (hunk 1 above)
Comment (gonfunko) [reply core/interfaces/i_rendered_element.ts:9]: Done
