### PR TITLE
Fix context menus on blocks with variables

### LINKED ISSUE #1658: Context menu create option shows id on blocks with variables
On blocks with variables, e.g. the "count with i from 1 to 10 by 1" loop block and, variable blocks themselves, the context menu option displays the variable id.

On this block:
screen shot 2018-02-23 at 10 33 59 am

The context menu looks like this:
screen shot 2018-02-23 at 10 32 48 am

### Steps to Reproduce
1. open loops category in the playground
2. drag in count with i from 1 to 10 by 1 block
3. right click to bring up the context menu

### Operating System and Browser
Mac Chrome. 
But probably all.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

Fixes #1658 

### Proposed Changes

Update the text of the custom context menu options to refer to the variable by name, not ID.
Update the generated XML to create a block that refers to the correct variable.

### Reason for Changes

The previous implementation worked when variable field values gave the name of the variable rather than ID.  I missed this when testing variable by ID changes.

### Test Coverage

Unit tests pass.
I loaded all blocks that have this type of context menu option (XML is in a comment on #1658) and checked that the right-click menu said the right thing and generated the right block when clicked.

### CODE REVIEW

File: core/variables.js [hunk 1]
```diff
@@ -439,21 +439,36 @@ Blockly.Variables.nameUsedWithAnyType_ = function(name, workspace) {
...
-    '" variabletype="' + goog.string.htmlEscape(typeString) +
-    '">' + goog.string.htmlEscape(variableModel.name) + '</field>';
+      '" variabletype="' + goog.string.htmlEscape(typeString) +
+      '">' + goog.string.htmlEscape(variableModel.name) + '</field>';
   return text;
 };
 
+/**
+ * Generate DOM objects representing a variable field.
+ * @param {!Blockly.VariableModel} variableModel The variable model represent.
```
Comment (AnmAtAnm) [inline core/variables.js]: "...model to represent." or "...model represented."?
