### PR TITLE
Fix plane demo bug.

### LINKED ISSUE #3639: Row block in plane demo incorrect location after connecting
**Describe the bug**
When you try to connect the row block in the plane demo it doesn't have the correct location.
This only happens when a user drags directly from the toolbox. If you drop the block on the workspace and then connect it will work as expected.

**To Reproduce**
1. Go to plane demo
2. Drag out a multiplication block
3. Drag out a row block and try to attach to multiplication block

**Expected behavior**

**Screenshots**
Screen Shot 2020-01-22 at 2 11 25 PM

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#3639

### Proposed Changes

Reduce unnecessary calls to update block field value by only updating when slider value changes and setting field label at init (rather than at Block.CREATE).

### Reason for Changes

Row blocks were misaligned when dragged directly from the toolbox. Reducing calls and setting field value on init prevents this issue.

### Additional Information

Filed bug #3773 to investigate further why there are issues with updating field value on trigger of Block.CREATE

### CODE REVIEW

File: demos/plane/plane.js [hunk 1]
```diff
@@ -200,12 +200,20 @@ Plane.rows1st = 0;
...
 /**
- * Redraw the rows when the slider has moved.
+ * Redraw the rows and update blocks when the slider has moved.
  * @param {number} value New slider position.
  */
 Plane.sliderChange = function(value) {
   var newRows = Math.round(value * 410 / 20);
   Plane.redraw(newRows);
+
+  function updateBlocks(blocks, verbose) {
```
Comment (alschmiedt) [inline demos/plane/plane.js]: is verbose getting used for anything?

Comment (moniika) [reply demos/plane/plane.js]: whoops, it was leftover from debugging. Will remove.
