### PR TITLE
Fix setting focus for workspace

### LINKED ISSUE #3364: Clicking workspace after comment resize causes a crash
**Describe the bug**

**To Reproduce**

1. Go to the playground
2. Drag any block onto the workspace and add a comment.
3. Resize the comment
4. Click on the workspace
5. See error in console.

**Expected behavior**

No error.

**Stack Traces**

```
blockly.js:343 Uncaught TypeError: Cannot read property 'trashcan' of null
    at Object.Blockly.hideChaff (blockly.js:343)
    at Blockly.TouchGesture.Blockly.Gesture.doStart (gesture.js:491)
    at Blockly.TouchGesture.doStart (touch_gesture.js:119)
    at Blockly.TouchGesture.Blockly.Gesture.handleWsStart (gesture.js:659)
    at Blockly.WorkspaceSvg.onMouseDown_ (workspace_svg.js:1392)
    at SVGGElement.wrapFunc (blockly.js:479)
```
**Additional context**

This is because workspace.onBlur is clearning Blockly.mainworkspace and a hideChaff is getting called when we click on the workspace.

The blur is getting called not because the injection div is blurred but one of its children is blurred (the comment text area).

@alschmiedt FYI

### PR DESCRIPTION
**Pull request by alschmiedt**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves
Fixes #3364.

### Proposed Changes
1. Use focusin and don't set the mainWorkspace on focusout
2. Add prevent scroll to focus 
3. hideChaff before marking workspace 
### Test Coverage

Tested on:

### CODE REVIEW

File: core/field_dropdown.js [hunk 1]
```diff
@@ -234,7 +234,7 @@ Blockly.FieldDropdown.prototype.showEditor_ = function() {
   // Focusing needs to be handled after the menu is rendered and positioned.
   // Otherwise it will cause a page scroll to get the misplaced menu in
   // view. See issue #1329.
-  this.menu_.focus();
+  this.menu_.focus({preventScroll:true});
```
Comment (samelhusseini) [inline core/field_dropdown.js]: This is just calling the menu's focus event not an element focus so no need here.
