### PR TITLE
Setting default options in workspace constructor.

### LINKED ISSUE #3459: Workspace options should always be parsed
**Describe the bug**

Because options are parsed in inject instead of the workspace constructor, you can get headless workspaces the opperate differently from svg workspaces. [https://groups.google.com/forum/#!topic/blockly/tfHCA7afoC0](https://groups.google.com/forum/#!topic/blockly/tfHCA7afoC0)

This also makes working with flyouts confusing, because while they do have workspaces they may not work as you first assume.

**To Reproduce**

1. Create a rendered workspace and a headless workspace. Pass options to neither.
2. Deserialize the following xml to both workspaces.

```
<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable>i</variable>
  </variables>
  <block type="variables_set">
    <field name="VAR">i</field>
    <value name="VALUE">
      <block type="lists_create_with">
        <mutation items="3"/>
        <value name="ADD0">
          <block type="text">
            <field name="TEXT">1</field>
          </block>
        </value>
        <value name="ADD1">
          <block type="text">
            <field name="TEXT">2</field>
          </block>
        </value>
        <value name="ADD2">
          <block type="text">
            <field name="TEXT">3</field>
          </block>
        </value>
      </block>
    </value>
    <next>
      <block type="text_print">
        <value name="TEXT">
          <shadow type="text">
            <field name="TEXT"/>
          </shadow>
          <block type="lists_getIndex">
            <mutation statement="false" at="true"/>
            <field name="MODE">GET</field>
            <field name="WHERE">FROM_START</field>
            <value name="VALUE">
              <block type="variables_get">
                <field name="VAR">i</field>
              </block>
            </value>
            <value name="AT">
              <block type="math_number">
                <field name="NUM">1</field>
              </block>
            </value>
          </block>
        </value>
      </block>
    </next>
  </block>
</xml>
```
3. Export both workspaces to javascript.

```
// Rendered.
var i;


i = ['1', '2', '3'];
window.alert(i[0]);
```

```
// Headless
var i;


i = ['1', '2', '3'];
window.alert(i[1]);  //Bad!
```
4. Observe how the headless workspace behaves differently.

**Expected behavior**

Both workspaces should result in `window.alert(i[0]);`.

**Additional context**

Flyouts, mutators, and mutator flyouts should get a thorough testing if this is fixed, because there may be code relying on their current behavior.

### PR DESCRIPTION
**Pull request by moniika**
## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

### Resolves

#3459

### Proposed Changes

Uses default `Blockly.Options` if it is not provided to the Workspace constructor.

### Reason for Changes

Before this change, the options set for workspaces through the constructor vs inject when no options were provided were different. This especially caused confusion for the option for oneBasedIndexing which can result in different code being generated.

### Test Coverage

Compared code generation between headless and non-headless workspaces without parameters provided.

Tested on:
* Desktop Chrome

### CODE REVIEW

File: core/workspace.js [hunk 1]
```diff
@@ -40,7 +41,7 @@ Blockly.Workspace = function(opt_options) {
   this.id = Blockly.utils.genUid();
   Blockly.Workspace.WorkspaceDB_[this.id] = this;
   /** @type {!Blockly.Options} */
-  this.options = opt_options || /** @type {!Blockly.Options} */ ({});
+  this.options = opt_options || new Blockly.Options({});
```
Comment (samelhusseini) [inline core/workspace.js]: Not sure this fixes the issue. This might use a better default if no options are passed, but what if a ``{}`` is passed in. It wouldn't go through Blockly.Options, and thus ``options.oneBasedIndex`` would be set to false.

Comment (moniika) [reply core/workspace.js]: I've updated the logic to be the same as in inject.

File: core/workspace.js [hunk 2]
```diff
@@ -40,7 +41,7 @@ Blockly.Workspace = function(opt_options) {
   this.id = Blockly.utils.genUid();
   Blockly.Workspace.WorkspaceDB_[this.id] = this;
   /** @type {!Blockly.Options} */
-  this.options = opt_options || /** @type {!Blockly.Options} */ ({});
+  this.options = new Blockly.Options(opt_options || {});
```
Comment (samelhusseini) [inline core/workspace.js]: This makes sense for headless, but in rendered mode a Blockly.WorkspaceSvg instance calls it's super constructor with a options object of type ``Blockly.Options``. This would now pipe that Blockly.Options object into another Blockly.Options object.

Comment (moniika) [reply core/workspace.js]: Good point. Looking more thoroughly through the code, changing the reference of the options object causes issues with non-headless and also I didn't realize there was a `Blockly.Options` and a `Blockly.BlocklyOptions`.

Given this, I think the earlier solution of:
`opt_options || new Blockly.Options({});`
makes more sense here.

File: core/workspace.js (hunk 1 above)
Comment (moniika) [reply core/workspace.js]: Changed back after noticing there is `Blockly.Options` and a `Blockly.BlocklyOptions`,
I think this makes sense here because if someone was to pass an empty object, it would actually be the wrong type and I think its fine that it isn't parsed.
This fixes the inconsistency between the constructor with no option passed and inject with no option passed.

Comment (samelhusseini) [reply core/workspace.js]: Okay that makes sense. In which case, I would update any of our tests that pass in an object in the constructor to instead wrap that object with a Blockly.Options object.

File: core/inject.js [hunk 3]
```diff
@@ -77,7 +77,7 @@ Blockly.inject = function(container, opt_options) {
 
   var workspace = Blockly.createMainWorkspace_(svg, options, blockDragSurface,
       workspaceDragSurface);
-  Blockly.user.keyMap.setKeyMap(options.keyMap);
+  Blockly.user.keyMap.setKeyMap(workspace.options.keyMap);
```
Comment (samelhusseini) [inline core/inject.js]: Why not continue using options? workspace.options should be == options.

File: core/options.js [hunk 4]
```diff
@@ -155,6 +155,12 @@ Blockly.Options = function(options) {
  */
 Blockly.BlocklyOptions = function() {};
 
+/**
+ * The SVG element for the grid pattern.
+ * @type {SVGElement}
+ */
+Blockly.Options.prototype.gridPattern = null;
```
Comment (samelhusseini) [inline core/options.js]: Can we move this to the constructor.

File: core/workspace.js (hunk 1 above)
Comment (moniika) [reply core/workspace.js]: Test have been updated.

File: core/options.js (hunk 4 above)
Comment (samelhusseini) [reply core/options.js]: Even if it's not passed into the options and you just want to set it to ``null``. I would set it in the constructor as per https://github.com/google/blockly/issues/2892

Comment (moniika) [reply core/options.js]: Updated.

File: core/inject.js (hunk 3 above)
Comment (moniika) [reply core/inject.js]: Changed back.

File: core/mutator.js [hunk 5]
```diff
@@ -161,21 +161,23 @@ Blockly.Mutator.prototype.createEditor_ = function() {
...
-    toolboxPosition: this.block_.RTL ? Blockly.TOOLBOX_AT_RIGHT :
-        Blockly.TOOLBOX_AT_LEFT,
-    horizontalLayout: false,
-    getMetrics: this.getFlyoutMetrics_.bind(this),
-    setMetrics: null,
-    renderer: this.block_.workspace.options.renderer
-  });
+  var workspaceOptions = new Blockly.Options(
+      /** @type {!Blockly.BlocklyOptions} */
+      ({
```
Comment (mattbishop) [inline core/mutator.js]: Just curious, why are you wrapping the options object in a closure?

Comment (alschmiedt) [reply core/mutator.js]: I think she is just casting the options to the correct type so that it passes our type checks.
